"""ORIGIN: an ordinal grade generated by conserved local transition rates.

The model has one prediction path.  Spatial cells emit non-negative evidence
for adjacent ordinal transitions, those contributions add to a conservative
pure-birth generator, and the endpoint distribution of that generator is the
grade distribution.  There is no pooled classifier, residual logit, or other
route around the reported local ledger.

The generator is useful beyond retinal grading, but the structural prior is
specifically ordinal: a severity atom at level ``m`` can support every
prerequisite transition ``k <= m``.  ``atom_mode='independent'`` is retained
as a matched ablation; ``'hybrid'`` learns how strongly to impose that prior.

Rates are latent evidence-transition rates at a fixed unit endpoint.  They are
not estimates of biological time or longitudinal disease progression.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
import math
from typing import Dict, Mapping, Optional, Sequence, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F

from .origin_encoder import (
    ConvNeXtTinyPyramidEncoder,
    ConvNeXtTinySRFFEncoder,
    OriginEncoderOutput,
    OriginEncoderScale,
    OriginScaleMetadata,
)


_ATOM_MODES = frozenset(("cumulative", "independent", "hybrid"))
_DECODER_DTYPE = torch.float64
_EXP_TAYLOR_DEGREE = 24
_EXP_SCALING_THETA = 0.5
_MAX_DECODER_RATE = 700.0


def _require_finite(tensor: torch.Tensor, name: str) -> None:
    if not torch.isfinite(tensor).all():
        nan = int(torch.isnan(tensor).sum().item())
        pos = int(torch.isposinf(tensor).sum().item())
        neg = int(torch.isneginf(tensor).sum().item())
        raise FloatingPointError(
            f"{name} contains non-finite values "
            f"(nan={nan}, +inf={pos}, -inf={neg})"
        )


def _inverse_sigmoid_fraction(value: float, maximum: float, *, name: str) -> float:
    """Return the logit whose bounded sigmoid equals ``value``.

    Keeping bounded parameter initialisation explicit avoids silently changing
    ORIGIN's near-null starting law when replacing the former unbounded
    softplus parameterisation.
    """

    value = float(value)
    maximum = float(maximum)
    if not math.isfinite(maximum) or maximum <= 0.0:
        raise ValueError(f"{name} maximum must be finite and positive")
    if not math.isfinite(value) or not 0.0 < value < maximum:
        raise ValueError(f"{name} initialization must lie strictly in (0, maximum)")
    return math.log(value) - math.log(maximum - value)


def reverse_cumulative_atoms(atoms: torch.Tensor, *, dim: int = 1) -> torch.Tensor:
    """Compile incremental severity atoms into prerequisite evidence."""

    if atoms.ndim == 0:
        raise ValueError("atoms must have at least one dimension")
    if atoms.shape[dim] < 1:
        raise ValueError("the atom dimension must be non-empty")
    return atoms.flip((dim,)).cumsum(dim=dim).flip((dim,))


def pure_birth_generator(rates: torch.Tensor) -> torch.Tensor:
    """Construct a conservative upper-bidiagonal CTMC generator.

    Args:
        rates: Non-negative tensor with final dimension ``K-1``.

    Returns:
        Tensor with shape ``rates.shape[:-1] + (K, K)``.  Rows sum to zero,
        off-diagonal entries are non-negative, and state ``K-1`` is absorbing.
    """

    if rates.ndim < 1 or rates.shape[-1] < 1:
        raise ValueError("rates must have shape (..., K-1) with K >= 2")
    if not rates.is_floating_point():
        raise TypeError("rates must be floating point")
    _require_finite(rates, "pure-birth rates")
    if bool((rates < 0).any()):
        raise ValueError("pure-birth rates must be non-negative")

    zeros = torch.zeros_like(rates[..., :1])
    diagonal = torch.cat((-rates, zeros), dim=-1)
    return torch.diag_embed(diagonal) + torch.diag_embed(rates, offset=1)


def _stable_matrix_exp(matrix: torch.Tensor) -> torch.Tensor:
    """Evaluate a small matrix exponential using elementary FP64 operations.

    ``torch.matrix_exp`` has an accurate forward pass for ORIGIN's generator,
    but its generic backward can be catastrophically inaccurate for the
    highly non-normal, unequal-rate upper-bidiagonal matrices encountered in
    training.  This implementation first scales every matrix in the batch so
    its infinity norm is at most 0.5, evaluates the degree-24 Taylor series,
    and then squares back to the requested scale.  Autograd therefore sees
    only additions and matrix multiplications.  The Taylor remainder at the
    scaled norm is below FP64 roundoff for this decoder.

    The integer scaling choice is made from a detached norm.  It changes only
    the numerical evaluation graph, not the represented matrix exponential.
    """

    if matrix.ndim < 2 or matrix.shape[-1] != matrix.shape[-2]:
        raise ValueError("matrix must have shape (..., K, K)")
    if matrix.dtype != _DECODER_DTYPE:
        raise TypeError("the stable matrix exponential requires FP64 input")
    _require_finite(matrix, "stable matrix-exponential input")

    norm = matrix.detach().abs().sum(dim=-1).amax()
    norm_value = float(norm.item())
    if norm_value <= _EXP_SCALING_THETA:
        squarings = 0
    else:
        squarings = int(
            math.ceil(math.log2(norm_value / _EXP_SCALING_THETA))
        )
    scale = math.ldexp(1.0, squarings)
    scaled = matrix / scale

    size = matrix.shape[-1]
    identity = torch.eye(size, dtype=matrix.dtype, device=matrix.device)
    identity = identity.expand(matrix.shape[:-2] + (size, size))
    result = identity
    term = identity
    for order in range(1, _EXP_TAYLOR_DEGREE + 1):
        term = torch.matmul(term, scaled) / float(order)
        result = result + term
    for _ in range(squarings):
        result = torch.matmul(result, result)
    return result


@dataclass
class OriginDecodedDistribution:
    """Endpoint law produced by a pure-birth ordinal generator."""

    total_rates: torch.Tensor
    generator: torch.Tensor
    transition_matrix: torch.Tensor
    class_probs: torch.Tensor
    log_class_probs: torch.Tensor
    cumulative_probs: torch.Tensor
    expected_grade: torch.Tensor
    posterior_median: torch.Tensor
    class_map: torch.Tensor

    @property
    def predicted_grade(self) -> torch.Tensor:
        """Accuracy-oriented public default; explicit alternatives are stored."""

        return self.class_map

    @property
    def monotone_grade(self) -> torch.Tensor:
        """Posterior-median decision with monotone rate interventions."""

        return self.posterior_median

    # Explicit aliases make the object easy to consume beside older trainers.
    @property
    def class_probabilities(self) -> torch.Tensor:
        return self.class_probs

    @property
    def log_class_probabilities(self) -> torch.Tensor:
        return self.log_class_probs

    @property
    def cumulative_probabilities(self) -> torch.Tensor:
        return self.cumulative_probs


def decode_pure_birth_rates(
    rates: torch.Tensor,
    *,
    force_fp64: bool = True,
    probability_tolerance: float = 5e-12,
) -> OriginDecodedDistribution:
    """Evolve a unit-time pure-birth chain from grade zero.

    The structural decoder is always evaluated in FP64 with an audited Taylor
    scaling-and-squaring exponential.  This is an invariant, not a tunable
    precision option: generic matrix-exponential backward kernels can return
    incorrect gradients for ORIGIN's high, unequal transition rates.  The
    source rate ledger is retained in its original dtype while the generator,
    posterior, and log posterior remain FP64 through the training loss.
    """

    if not math.isfinite(probability_tolerance) or probability_tolerance < 0:
        raise ValueError("probability_tolerance must be finite and non-negative")
    if not force_fp64:
        raise ValueError("ORIGIN's structural decoder must run in FP64")
    if rates.ndim < 1 or rates.shape[-1] < 1 or rates.numel() < 1:
        raise ValueError("rates must have non-empty shape (..., K-1) with K >= 2")
    if not rates.is_floating_point():
        raise TypeError("rates must be floating point")
    _require_finite(rates, "pure-birth rates")
    if bool((rates < 0).any()):
        raise ValueError("pure-birth rates must be non-negative")
    maximum_rate = float(rates.detach().amax().item())
    if maximum_rate > _MAX_DECODER_RATE:
        raise FloatingPointError(
            "pure-birth rate exceeds the audited FP64 decoder range "
            f"[0, {_MAX_DECODER_RATE:g}]: {maximum_rate:g}"
        )
    decoder_rates = rates.to(dtype=_DECODER_DTYPE)
    generator = pure_birth_generator(decoder_rates)

    # Disable any outer autocast region. Probabilities and their logs must stay
    # FP64; exp(-141), already seen in a run, underflows in FP32.
    device_type = generator.device.type
    with torch.autocast(device_type=device_type, enabled=False):
        transition = _stable_matrix_exp(generator)
    _require_finite(transition, "pure-birth transition matrix")

    probabilities = transition[..., 0, :]
    if bool((probabilities < 0.0).any()):
        minimum = float(probabilities.min().item())
        raise FloatingPointError(
            "stable matrix exponential produced a negative probability "
            f"({minimum})"
        )
    # Do not clamp or renormalize the posterior. Either operation could hide a
    # catastrophic relative error in a clinically rare class and would modify
    # the exact generator law and its intervention derivatives.
    row_error = (probabilities.sum(dim=-1) - 1.0).abs()
    if bool((row_error > probability_tolerance).any()):
        maximum_error = float(row_error.max().item())
        raise FloatingPointError(
            "stable matrix exponential violated probability conservation "
            f"(maximum row-sum error={maximum_error:g})"
        )
    _require_finite(probabilities, "pure-birth class probabilities")

    cumulative = probabilities[..., 1:].flip((-1,)).cumsum(dim=-1).flip((-1,))
    grade_axis = torch.arange(
        probabilities.shape[-1],
        device=probabilities.device,
        dtype=probabilities.dtype,
    )
    expected = (probabilities * grade_axis).sum(dim=-1)
    median = (cumulative >= 0.5).sum(dim=-1)
    class_map = probabilities.argmax(dim=-1)
    tiny = torch.finfo(probabilities.dtype).tiny
    log_probabilities = probabilities.clamp_min(tiny).log()

    return OriginDecodedDistribution(
        total_rates=rates,
        generator=generator,
        transition_matrix=transition,
        class_probs=probabilities,
        log_class_probs=log_probabilities,
        cumulative_probs=cumulative,
        expected_grade=expected,
        posterior_median=median,
        class_map=class_map,
    )


def bounded_rate_log_odds_merge(
    base_rates: torch.Tensor,
    cumulative_log_odds: torch.Tensor,
    *,
    total_rate_cap: float,
) -> torch.Tensor:
    """Apply a bounded relational correction to transition-rate log-odds.

    For a pre-relation rate ``lambda`` and cumulative pair field ``D``, the
    represented law is

    ``C * sigmoid(log(lambda) - log(C - lambda) + D)``.

    The computation stays in FP64.  A numerically reconstructed zero-shift
    value is subtracted before adding the correction to ``base_rates``.  This
    is algebraically identical to the expression above, while making an
    exactly zero pair field an exact machine-level identity with a non-zero
    derivative with respect to ``D``.  ORIGIN's one-unit roundoff reserve
    keeps the base rate strictly inside ``(0, C)``.
    """

    if base_rates.shape != cumulative_log_odds.shape:
        raise ValueError(
            "base_rates and cumulative_log_odds must have identical shapes; "
            f"got {tuple(base_rates.shape)} and {tuple(cumulative_log_odds.shape)}"
        )
    if not base_rates.is_floating_point() or not cumulative_log_odds.is_floating_point():
        raise TypeError("rate-log-odds merge inputs must be floating point")
    if not math.isfinite(total_rate_cap) or total_rate_cap <= 0.0:
        raise ValueError("total_rate_cap must be finite and positive")
    _require_finite(base_rates, "pre-relation transition rates")
    _require_finite(cumulative_log_odds, "cumulative pair log-odds")

    device_type = base_rates.device.type
    with torch.autocast(device_type=device_type, enabled=False):
        rates = base_rates.to(dtype=_DECODER_DTYPE)
        correction = cumulative_log_odds.to(device=rates.device, dtype=_DECODER_DTYPE)
        cap = torch.as_tensor(total_rate_cap, dtype=rates.dtype, device=rates.device)
        if bool(((rates <= 0.0) | (rates >= cap)).any()):
            minimum = float(rates.detach().amin().item())
            maximum = float(rates.detach().amax().item())
            raise ValueError(
                "pre-relation rates must lie strictly inside (0, total_rate_cap); "
                f"observed [{minimum:g}, {maximum:g}] with cap {total_rate_cap:g}"
            )
        base_log_odds = rates.log() - (cap - rates).log()
        reconstructed_zero = cap * base_log_odds.sigmoid()
        shifted = cap * (base_log_odds + correction).sigmoid()
        # Parentheses are intentional: when correction is exactly zero, the
        # subtraction is exactly zero before it is added to the original rate.
        merged = rates + (shifted - reconstructed_zero)

    _require_finite(merged, "relation-corrected transition rates")
    if bool(((merged <= 0.0) | (merged >= total_rate_cap)).any()):
        minimum = float(merged.detach().amin().item())
        maximum = float(merged.detach().amax().item())
        raise FloatingPointError(
            "bounded relational merge left the open decoder interval "
            f"(0, {total_rate_cap:g}); observed [{minimum:g}, {maximum:g}]"
        )
    return merged


def fit_pure_birth_rates(
    class_probs: torch.Tensor | Sequence[float],
    *,
    tolerance: float = 1e-10,
    max_iterations: int = 160,
    maximum_rate: float = _MAX_DECODER_RATE,
) -> torch.Tensor:
    """Invert one interior categorical law into unit-time birth rates.

    This is a mathematical/diagnostic helper, not ORIGIN's default prior
    initialization.  Image evidence only increases rates, so initializing the
    model's null prior to an imbalanced population law would prevent normal
    images from becoming highly confident grade zero.

    The first rate is ``-log(p_0)``.  Each later rate is found by bisection:
    with earlier rates fixed, endpoint mass in the current state decreases
    continuously from the remaining tail mass to zero as that rate grows.
    """

    probabilities = torch.as_tensor(class_probs, dtype=torch.float64)
    if probabilities.ndim != 1 or probabilities.numel() < 2:
        raise ValueError("class_probs must be a one-dimensional K>=2 vector")
    _require_finite(probabilities, "target class probabilities")
    if bool((probabilities <= 0).any()):
        raise ValueError("all target class probabilities must be strictly positive")
    if not math.isfinite(tolerance) or tolerance <= 0:
        raise ValueError("tolerance must be finite and positive")
    if max_iterations < 1:
        raise ValueError("max_iterations must be positive")
    if not math.isfinite(maximum_rate) or maximum_rate <= 0:
        raise ValueError("maximum_rate must be finite and positive")

    probabilities = probabilities / probabilities.sum()
    boundaries = probabilities.numel() - 1
    rates = torch.zeros(boundaries, dtype=torch.float64)
    rates[0] = -probabilities[0].log()

    for state in range(1, boundaries):
        target = float(probabilities[state].item())
        low = 0.0
        high = max(1.0, float(rates[:state].max().item()))

        def state_probability(candidate: float) -> float:
            trial = rates.clone()
            trial[state] = candidate
            decoded = decode_pure_birth_rates(trial, force_fp64=True)
            return float(decoded.class_probs[state].item())

        while state_probability(high) > target and high < maximum_rate:
            high = min(maximum_rate, high * 2.0)
        if state_probability(high) > target:
            raise RuntimeError(
                f"failed to bracket rate {state} below maximum_rate={maximum_rate}"
            )
        for _ in range(max_iterations):
            middle = (low + high) / 2.0
            value = state_probability(middle)
            if abs(value - target) <= tolerance:
                low = high = middle
                break
            if value > target:
                low = middle
            else:
                high = middle
        rates[state] = (low + high) / 2.0
    return rates


class ChannelLayerNorm2d(nn.Module):
    """LayerNorm over channels independently at every spatial cell."""

    def __init__(self, channels: int, eps: float = 1e-6) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.ones(channels))
        self.bias = nn.Parameter(torch.zeros(channels))
        self.eps = float(eps)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x.permute(0, 2, 3, 1)
        x = F.layer_norm(x, (x.shape[-1],), self.weight, self.bias, self.eps)
        return x.permute(0, 3, 1, 2).contiguous()


class PointwiseSeverityAtomHead(nn.Module):
    """A channel-only MLP that emits a bounded local severity measure.

    In cumulative/hybrid modes, each cell distributes a fixed finite mass
    budget between the ordinal severity atoms and an explicit null atom. In
    the matched independent ablation, each boundary instead receives its own
    bounded sigmoid atom so boundaries do not compete. Both constructions are
    non-negative and guarantee the per-boundary ``atom_mass_cap`` used by the
    generator's proof-level rate bound.
    """

    def __init__(
        self,
        in_channels: int,
        hidden_channels: int,
        num_boundaries: int,
        *,
        atom_rate_init: float = 1e-4,
        atom_mass_cap: float = 1.0,
        atom_mode: str = "cumulative",
        dropout: float = 0.0,
    ) -> None:
        super().__init__()
        if min(in_channels, hidden_channels, num_boundaries) < 1:
            raise ValueError("head dimensions must be positive")
        if not 0.0 <= dropout < 1.0:
            raise ValueError("dropout must lie in [0, 1)")
        if not math.isfinite(atom_mass_cap) or atom_mass_cap <= 0.0:
            raise ValueError("atom_mass_cap must be finite and positive")
        atom_mode = str(atom_mode).lower()
        if atom_mode not in _ATOM_MODES:
            raise ValueError(f"atom_mode must be one of {sorted(_ATOM_MODES)}")
        initial_fraction = float(atom_rate_init) / float(atom_mass_cap)
        active_multiplicity = 1 if atom_mode == "independent" else num_boundaries
        null_fraction = 1.0 - active_multiplicity * initial_fraction
        if (
            not math.isfinite(initial_fraction)
            or initial_fraction <= 0.0
            or null_fraction <= 0.0
        ):
            raise ValueError(
                "atom_rate_init must be positive and leave non-zero null mass "
                "inside atom_mass_cap"
            )
        self.num_boundaries = int(num_boundaries)
        self.atom_mass_cap = float(atom_mass_cap)
        self.atom_mode = atom_mode
        self.projection = nn.Conv2d(in_channels, hidden_channels, 1)
        self.norm = ChannelLayerNorm2d(hidden_channels)
        self.activation = nn.GELU()
        self.dropout = nn.Dropout2d(dropout)
        self.atom_logits = nn.Conv2d(hidden_channels, num_boundaries, 1)
        nn.init.normal_(self.atom_logits.weight, mean=0.0, std=0.01)
        # For cumulative/hybrid modes, equal active logits b and a fixed null
        # logit zero give q_active/q_null=exp(b). For the independent ablation,
        # the same expression is the inverse sigmoid of each uncoupled atom.
        initial_logit = math.log(initial_fraction / null_fraction)
        nn.init.constant_(self.atom_logits.bias, initial_logit)

    def forward(self, features: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        if features.ndim != 4:
            raise ValueError("features must have shape (N,C,H,W)")
        x = self.projection(features)
        x = self.dropout(self.activation(self.norm(x)))
        logits = self.atom_logits(x)
        _require_finite(logits, "severity atom logits")
        if self.atom_mode == "independent":
            # Preserve a genuinely independent matched ablation: changing one
            # boundary atom does not suppress another through a shared simplex.
            atoms = logits.sigmoid() * self.atom_mass_cap
        else:
            null_logits = torch.zeros_like(logits[:, :1])
            atom_probabilities = torch.cat((logits, null_logits), dim=1).softmax(dim=1)
            atoms = atom_probabilities[:, : self.num_boundaries] * self.atom_mass_cap
        _require_finite(atoms, "severity atoms")
        return logits, atoms


def aggregate_ordinal_pair_messages(
    edge_messages: torch.Tensor,
    edge_valid_mask: torch.Tensor,
    region_valid_mask: torch.Tensor,
    *,
    delta_cap: float,
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Aggregate stored pair messages into a bounded cumulative rate field.

    ``edge_messages[n,m,i,j]`` is the signed message from source region ``j``
    to target region ``i`` for incremental severity atom ``m``.  The first
    aggregation is target-local and normalized only by immutable geometry.
    Valid targets are then averaged, and reverse cumulative compilation makes
    a high-severity interaction affect all prerequisite transition-rate
    log-odds.  Dividing the per-atom budget by the number of boundaries proves
    ``abs(cumulative_log_odds) <= delta_cap``.
    """

    if edge_messages.ndim != 4:
        raise ValueError("edge_messages must have shape (N,K-1,M,M)")
    batch, boundaries, targets, sources = edge_messages.shape
    if targets != sources:
        raise ValueError("edge_messages must use a square region-pair lattice")
    if edge_valid_mask.shape != (batch, targets, sources):
        raise ValueError(
            "edge_valid_mask must have shape (N,M,M); got "
            f"{tuple(edge_valid_mask.shape)}"
        )
    if region_valid_mask.shape != (batch, targets):
        raise ValueError(
            "region_valid_mask must have shape (N,M); got "
            f"{tuple(region_valid_mask.shape)}"
        )
    if boundaries < 1:
        raise ValueError("at least one ordinal boundary is required")
    if not math.isfinite(delta_cap) or delta_cap <= 0.0:
        raise ValueError("delta_cap must be finite and positive")
    if edge_valid_mask.dtype != torch.bool:
        edge_valid_mask = edge_valid_mask.bool()
    if region_valid_mask.dtype != torch.bool:
        region_valid_mask = region_valid_mask.bool()
    _require_finite(edge_messages, "ordinal pair messages")
    tolerance = 2e-6
    if bool((edge_messages.abs() > 1.0 + tolerance).any()):
        raise ValueError("ordinal pair messages must lie in [-1, 1]")

    masked_messages = torch.where(
        edge_valid_mask[:, None], edge_messages, torch.zeros_like(edge_messages)
    )
    source_count = edge_valid_mask.sum(dim=-1).to(edge_messages.dtype)
    source_normalizer = source_count.clamp_min(1.0).sqrt()
    target_raw = masked_messages.sum(dim=-1) / source_normalizer[:, None]
    incremental_cap = float(delta_cap) / float(boundaries)
    target_incremental = incremental_cap * target_raw.tanh()
    target_incremental = torch.where(
        region_valid_mask[:, None],
        target_incremental,
        torch.zeros_like(target_incremental),
    )
    _require_finite(target_incremental, "target-local ordinal pair log-odds")
    target_count = region_valid_mask.sum(dim=-1).to(edge_messages.dtype)
    if bool((target_count <= 0).any()):
        raise ValueError("every sample must contain at least one valid relation region")
    incremental = target_incremental.sum(dim=-1) / target_count[:, None]
    _require_finite(incremental, "incremental ordinal pair log-odds")
    cumulative = reverse_cumulative_atoms(incremental, dim=1)
    _require_finite(cumulative, "cumulative ordinal pair log-odds")
    if bool((cumulative.abs() > float(delta_cap) + tolerance).any()):
        raise FloatingPointError("cumulative ordinal pair field exceeded its bound")
    return target_incremental, incremental, cumulative


@dataclass
class OriginRelationEvidence:
    """Stored, replayable trace of ORIGIN's explicit regional interactions."""

    source_scale: str
    grid_size: Tuple[int, int]
    block_size: Tuple[int, int]
    region_valid_mask: torch.Tensor
    edge_valid_mask: torch.Tensor
    pair_gates: torch.Tensor
    edge_messages: torch.Tensor
    target_incremental_log_odds: torch.Tensor
    incremental_log_odds: torch.Tensor
    cumulative_log_odds: torch.Tensor
    region_centers_yx: torch.Tensor
    source_receptive_field: int
    region_receptive_field: int
    region_output_stride: int
    delta_cap: float

    @property
    def num_regions(self) -> int:
        return self.grid_size[0] * self.grid_size[1]


class OrdinalPairInteractionField(nn.Module):
    """Compile bounded two-region messages into cumulative rate log-odds.

    The field pools a deterministic set of non-overlapping feature-lattice
    blocks.  Their receptive-field-qualified supports in input pixels can
    overlap and are reported explicitly; the architecture therefore claims
    interactions between regional representations, not disjoint or pure
    lesion synergy.  Every raw edge message depends only on its target and
    source tokens plus their fixed relative displacement; there is no softmax
    denominator involving other regions.  The trilinear output weights are
    initialized to exactly zero, making this module an exact function-
    preserving extension of a trained ORIGIN-v3 generator.
    """

    def __init__(
        self,
        source_channels: int,
        num_boundaries: int,
        *,
        grid_size: int = 10,
        relation_dim: int = 64,
        head_dim: int = 16,
        delta_cap: float = 2.0,
    ) -> None:
        super().__init__()
        if min(source_channels, num_boundaries, grid_size, relation_dim, head_dim) < 1:
            raise ValueError("relation dimensions must be positive")
        if not math.isfinite(delta_cap) or delta_cap <= 0.0:
            raise ValueError("relation delta_cap must be finite and positive")
        self.source_channels = int(source_channels)
        self.num_boundaries = int(num_boundaries)
        self.grid_size = int(grid_size)
        self.relation_dim = int(relation_dim)
        self.head_dim = int(head_dim)
        self.delta_cap = float(delta_cap)

        self.token_projection = nn.Linear(self.source_channels, self.relation_dim)
        self.token_norm = nn.LayerNorm(self.relation_dim)
        self.query_projection = nn.Linear(
            self.relation_dim, self.num_boundaries * self.head_dim
        )
        self.key_projection = nn.Linear(
            self.relation_dim, self.num_boundaries * self.head_dim
        )
        displacement = 2 * self.grid_size - 1
        self.relative_bias = nn.Parameter(
            torch.zeros(self.num_boundaries, displacement, displacement)
        )
        # This is the sole pair-output parameter. Zero is both a strict forward
        # identity and a point with a non-zero first derivative through tanh.
        self.trilinear_weight = nn.Parameter(
            torch.zeros(self.num_boundaries, self.head_dim)
        )

        coordinate = torch.arange(self.grid_size)
        yy, xx = torch.meshgrid(coordinate, coordinate, indexing="ij")
        flat_y = yy.reshape(-1)
        flat_x = xx.reshape(-1)
        self.register_buffer(
            "relative_y_index",
            flat_y[:, None] - flat_y[None, :] + self.grid_size - 1,
            persistent=False,
        )
        self.register_buffer(
            "relative_x_index",
            flat_x[:, None] - flat_x[None, :] + self.grid_size - 1,
            persistent=False,
        )
        self.register_buffer(
            "self_edge_mask",
            torch.eye(self.grid_size * self.grid_size, dtype=torch.bool),
            persistent=False,
        )

    def _pool_regions(
        self,
        features: torch.Tensor,
        valid_mask: torch.Tensor,
    ) -> Tuple[torch.Tensor, torch.Tensor, Tuple[int, int]]:
        if features.ndim != 4 or features.shape[1] != self.source_channels:
            raise ValueError(
                "relation source features must have shape "
                f"(N,{self.source_channels},H,W)"
            )
        if valid_mask.shape != features.shape[:1] + features.shape[-2:]:
            raise ValueError("relation source valid-mask shape mismatch")
        if valid_mask.dtype != torch.bool:
            valid_mask = valid_mask.bool()
        batch, channels, height, width = features.shape
        grid = self.grid_size
        if height % grid or width % grid:
            raise ValueError(
                "relation source lattice dimensions must be divisible by "
                f"grid_size={grid}; got {(height, width)}"
            )
        block_height = height // grid
        block_width = width // grid
        mask = valid_mask[:, None].to(features.dtype)
        weighted = (features * mask).reshape(
            batch, channels, grid, block_height, grid, block_width
        ).sum(dim=(3, 5))
        counts = mask.reshape(
            batch, 1, grid, block_height, grid, block_width
        ).sum(dim=(3, 5))
        pooled = weighted / counts.clamp_min(1.0)
        minimum_count = 0.5 * float(block_height * block_width)
        region_valid = counts[:, 0] >= minimum_count
        pooled = torch.where(
            region_valid[:, None], pooled, torch.zeros_like(pooled)
        )
        pooled = pooled.permute(0, 2, 3, 1).reshape(
            batch, grid * grid, channels
        )
        return pooled, region_valid.reshape(batch, -1), (block_height, block_width)

    def forward(
        self,
        encoded: OriginEncoderScale,
    ) -> OriginRelationEvidence:
        features = encoded.features.float()
        _require_finite(features, "relation source features")
        pooled, region_valid, block_size = self._pool_regions(
            features, encoded.valid_mask
        )
        _require_finite(pooled, "pooled relation region features")
        tokens = F.gelu(self.token_norm(self.token_projection(pooled)))
        _require_finite(tokens, "relation region tokens")
        batch, regions, _ = tokens.shape
        queries = self.query_projection(tokens).reshape(
            batch, regions, self.num_boundaries, self.head_dim
        ).permute(0, 2, 1, 3)
        keys = self.key_projection(tokens).reshape(
            batch, regions, self.num_boundaries, self.head_dim
        ).permute(0, 2, 1, 3)
        _require_finite(queries, "relation pair queries")
        _require_finite(keys, "relation pair keys")

        inverse_sqrt = 1.0 / math.sqrt(float(self.head_dim))
        affinity = torch.einsum("nbih,nbjh->nbij", queries, keys) * inverse_sqrt
        _require_finite(affinity, "relation content affinities")
        relative = self.relative_bias[
            :, self.relative_y_index, self.relative_x_index
        ]
        _require_finite(relative, "relation relative-position biases")
        affinity = affinity + relative[None]
        _require_finite(affinity, "raw relation pair affinities")
        pair_gates = affinity.sigmoid()
        _require_finite(pair_gates, "relation pair gates")
        trilinear = torch.einsum(
            "nbih,bh,nbjh->nbij", queries, self.trilinear_weight, keys
        ) * inverse_sqrt
        _require_finite(trilinear, "raw relation trilinear messages")

        edge_valid = (
            region_valid[:, :, None]
            & region_valid[:, None, :]
            & ~self.self_edge_mask[None]
        )
        pair_gates = torch.where(
            edge_valid[:, None], pair_gates, torch.zeros_like(pair_gates)
        )
        edge_messages = torch.where(
            edge_valid[:, None],
            pair_gates * trilinear.tanh(),
            torch.zeros_like(trilinear),
        )
        _require_finite(pair_gates, "masked relation pair gates")
        _require_finite(edge_messages, "masked relation edge messages")
        target_incremental, incremental, cumulative = aggregate_ordinal_pair_messages(
            edge_messages,
            edge_valid,
            region_valid,
            delta_cap=self.delta_cap,
        )

        metadata = encoded.metadata
        block_height, block_width = block_size
        region_receptive_field = int(
            metadata.receptive_field
            + (max(block_height, block_width) - 1) * metadata.output_stride
        )
        if block_height != block_width:
            raise ValueError("relation endpoint blocks must be square")
        region_stride = int(metadata.output_stride * block_height)
        first_center = metadata.center_offset + 0.5 * (
            block_height - 1
        ) * metadata.output_stride
        axis = first_center + torch.arange(
            self.grid_size, device=features.device, dtype=features.dtype
        ) * region_stride
        center_y, center_x = torch.meshgrid(axis, axis, indexing="ij")
        centers = torch.stack((center_y, center_x), dim=-1).reshape(regions, 2)
        _require_finite(target_incremental, "relation target log-odds output")
        _require_finite(incremental, "relation incremental log-odds output")
        _require_finite(cumulative, "relation cumulative log-odds output")
        _require_finite(centers, "relation endpoint centers")
        return OriginRelationEvidence(
            source_scale=metadata.name,
            grid_size=(self.grid_size, self.grid_size),
            block_size=block_size,
            region_valid_mask=region_valid,
            edge_valid_mask=edge_valid,
            pair_gates=pair_gates,
            edge_messages=edge_messages,
            target_incremental_log_odds=target_incremental,
            incremental_log_odds=incremental,
            cumulative_log_odds=cumulative,
            region_centers_yx=centers,
            source_receptive_field=int(metadata.receptive_field),
            region_receptive_field=region_receptive_field,
            region_output_stride=region_stride,
            delta_cap=self.delta_cap,
        )


@dataclass
class OriginScaleEvidence:
    """Replayable evidence ledger for one spatial scale."""

    name: str
    atom_logits: torch.Tensor
    incremental_atoms: torch.Tensor
    compiled_atoms: torch.Tensor
    local_rate_map: torch.Tensor
    valid_mask: torch.Tensor
    geometry_weight: torch.Tensor
    scale_weights: torch.Tensor
    metadata: OriginScaleMetadata

    @property
    def rate_contributions(self) -> torch.Tensor:
        return self.local_rate_map


@dataclass
class OriginOutput:
    """Complete prediction trace; all grade probabilities derive from ledger."""

    scale_evidence: Dict[str, OriginScaleEvidence]
    prior_rates: torch.Tensor
    total_rates: torch.Tensor
    generator: torch.Tensor
    transition_matrix: torch.Tensor
    class_probs: torch.Tensor
    log_class_probs: torch.Tensor
    cumulative_probs: torch.Tensor
    expected_grade: torch.Tensor
    posterior_median: torch.Tensor
    class_map: torch.Tensor
    atom_mode: str
    scale_simplex: torch.Tensor
    boundary_scales: torch.Tensor
    total_rate_cap: float
    prior_rate_cap: float
    boundary_scale_cap: float
    atom_mass_cap: float
    rate_roundoff_margin: float
    encoder_output: Optional[OriginEncoderOutput] = None
    # ``base_total_rates`` is the conserved v3 ledger before any relational
    # correction.  Keeping it alongside the final rates makes both local-cell
    # and pair-edge interventions exact replays of the prediction circuit.
    base_total_rates: Optional[torch.Tensor] = None
    relation_evidence: Optional[OriginRelationEvidence] = None

    @property
    def pre_relation_rates(self) -> torch.Tensor:
        """Conserved v3 rate ledger used as input to the relation merge."""

        return self.total_rates if self.base_total_rates is None else self.base_total_rates

    @property
    def local_rate_maps(self) -> Dict[str, torch.Tensor]:
        """Local rate ledgers in spatial-first ``(N,H,W,K-1)`` layout."""

        return {
            name: evidence.local_rate_map.permute(0, 2, 3, 1)
            for name, evidence in self.scale_evidence.items()
        }

    @property
    def local_rate_maps_channels_first(self) -> Dict[str, torch.Tensor]:
        """Internal convolution-layout views with shape ``(N,K-1,H,W)``."""

        return {
            name: evidence.local_rate_map
            for name, evidence in self.scale_evidence.items()
        }

    @property
    def valid_masks(self) -> Dict[str, torch.Tensor]:
        return {
            name: evidence.valid_mask
            for name, evidence in self.scale_evidence.items()
        }

    @property
    def metadata(self) -> Dict[str, OriginScaleMetadata]:
        return {
            name: evidence.metadata
            for name, evidence in self.scale_evidence.items()
        }

    @property
    def predicted_grade(self) -> torch.Tensor:
        return self.class_map

    @property
    def monotone_grade(self) -> torch.Tensor:
        return self.posterior_median

    @property
    def class_probabilities(self) -> torch.Tensor:
        return self.class_probs

    @property
    def log_class_probabilities(self) -> torch.Tensor:
        return self.log_class_probs

    @property
    def cumulative_probabilities(self) -> torch.Tensor:
        return self.cumulative_probs


def _origin_output_from_decoded(
    decoded: OriginDecodedDistribution,
    *,
    scale_evidence: Dict[str, OriginScaleEvidence],
    prior_rates: torch.Tensor,
    atom_mode: str,
    scale_simplex: torch.Tensor,
    boundary_scales: torch.Tensor,
    total_rate_cap: float,
    prior_rate_cap: float,
    boundary_scale_cap: float,
    atom_mass_cap: float,
    rate_roundoff_margin: float,
    encoder_output: Optional[OriginEncoderOutput],
    base_total_rates: Optional[torch.Tensor] = None,
    relation_evidence: Optional[OriginRelationEvidence] = None,
) -> OriginOutput:
    return OriginOutput(
        scale_evidence=scale_evidence,
        prior_rates=prior_rates,
        total_rates=decoded.total_rates,
        generator=decoded.generator,
        transition_matrix=decoded.transition_matrix,
        class_probs=decoded.class_probs,
        log_class_probs=decoded.log_class_probs,
        cumulative_probs=decoded.cumulative_probs,
        expected_grade=decoded.expected_grade,
        posterior_median=decoded.posterior_median,
        class_map=decoded.class_map,
        atom_mode=atom_mode,
        scale_simplex=scale_simplex,
        boundary_scales=boundary_scales,
        total_rate_cap=total_rate_cap,
        prior_rate_cap=prior_rate_cap,
        boundary_scale_cap=boundary_scale_cap,
        atom_mass_cap=atom_mass_cap,
        rate_roundoff_margin=rate_roundoff_margin,
        encoder_output=encoder_output,
        base_total_rates=(
            decoded.total_rates if base_total_rates is None else base_total_rates
        ),
        relation_evidence=relation_evidence,
    )


def sum_local_rate_maps(
    local_rate_maps: Mapping[str, torch.Tensor],
    prior_rates: torch.Tensor,
) -> torch.Tensor:
    """Conserve all local contributions into one boundary-rate vector."""

    if not local_rate_maps:
        raise ValueError("at least one local rate map is required")
    result = prior_rates
    for name, rate_map in local_rate_maps.items():
        if rate_map.ndim != 4:
            raise ValueError(
                f"local rate map {name!r} must have shape (N,K-1,H,W)"
            )
        if tuple(rate_map.shape[:2]) != tuple(prior_rates.shape):
            raise ValueError(
                f"local rate map {name!r} has incompatible batch/boundary shape"
            )
        _require_finite(rate_map, f"local rate map {name}")
        if bool((rate_map < 0).any()):
            raise ValueError(f"local rate map {name!r} must be non-negative")
        result = result + rate_map.to(dtype=result.dtype).sum(dim=(-2, -1))
    _require_finite(result, "conserved total rates")
    return result


class ConservedOrdinalGenerator(nn.Module):
    """Compile multi-scale feature cells into a pure-birth ordinal law.

    ``reference_count`` controls the exposure represented by a complete valid
    map at every scale.  Runtime geometry weights make the *original* valid
    map sum to this fixed exposure.  A value near the number of stride-8 cells
    retains useful dynamic range for a focal witness; the correspondingly tiny
    ``atom_rate_init`` keeps the initial image-level rate near zero.  The
    geometry weight is stored and is never recomputed during intervention.
    """

    def __init__(
        self,
        *,
        stage_channels: Mapping[str, int],
        num_classes: int = 5,
        hidden_channels: int = 128,
        evidence_scales: Optional[Sequence[str]] = None,
        reference_count: float = 4096.0,
        atom_mode: str = "cumulative",
        hybrid_cumulative_init: float = 0.9,
        atom_rate_init: float = 1e-6,
        prior_rate_init: float = 1e-4,
        boundary_scale_init: float = 1.0,
        total_rate_cap: float = 64.0,
        prior_rate_cap: float = 1.0,
        boundary_scale_cap: float = 2.0,
        rate_roundoff_margin: float = 1.0,
        dropout: float = 0.0,
        relation_enabled: bool = False,
        relation_source_scale: str = "s8",
        relation_grid_size: int = 10,
        relation_dim: int = 64,
        relation_head_dim: int = 16,
        relation_delta_cap: float = 2.0,
    ) -> None:
        super().__init__()
        if num_classes < 2:
            raise ValueError("num_classes must be at least 2")
        if num_classes == 2:
            # Supported exactly for tests and binary ablations; the proposed
            # cumulative ordinal mechanism becomes non-trivial only at K>=3.
            pass
        if not math.isfinite(reference_count) or reference_count <= 0:
            raise ValueError("reference_count must be finite and positive")
        if not math.isfinite(total_rate_cap) or total_rate_cap <= 0.0:
            raise ValueError("total_rate_cap must be finite and positive")
        if total_rate_cap > _MAX_DECODER_RATE:
            raise ValueError(
                "total_rate_cap must not exceed the audited decoder limit "
                f"{_MAX_DECODER_RATE:g}"
            )
        if not math.isfinite(prior_rate_cap) or not 0.0 < prior_rate_cap < total_rate_cap:
            raise ValueError("prior_rate_cap must lie strictly in (0, total_rate_cap)")
        if not math.isfinite(boundary_scale_cap) or boundary_scale_cap <= 0.0:
            raise ValueError("boundary_scale_cap must be finite and positive")
        if (
            not math.isfinite(rate_roundoff_margin)
            or rate_roundoff_margin <= 0.0
            or rate_roundoff_margin >= total_rate_cap - prior_rate_cap
        ):
            raise ValueError(
                "rate_roundoff_margin must lie strictly in "
                "(0, total_rate_cap - prior_rate_cap)"
            )
        atom_mode = str(atom_mode).lower()
        if atom_mode not in _ATOM_MODES:
            raise ValueError(f"atom_mode must be one of {sorted(_ATOM_MODES)}")
        if not 0.0 < hybrid_cumulative_init < 1.0:
            raise ValueError("hybrid_cumulative_init must lie strictly in (0, 1)")
        if not stage_channels:
            raise ValueError("stage_channels must not be empty")

        available = dict(stage_channels)
        selected = tuple(available) if evidence_scales is None else tuple(evidence_scales)
        if not selected or len(set(selected)) != len(selected):
            raise ValueError("evidence_scales must contain unique stage names")
        unknown = set(selected) - set(available)
        if unknown:
            raise ValueError(f"unknown evidence scales: {sorted(unknown)}")
        relation_source_scale = str(relation_source_scale)
        if relation_enabled and relation_source_scale not in available:
            raise ValueError(
                "relation_source_scale must be exposed by the encoder; "
                f"got {relation_source_scale!r}, available={sorted(available)}"
            )

        self.num_classes = int(num_classes)
        self.num_boundaries = self.num_classes - 1
        self.evidence_scales = selected
        self.reference_count = float(reference_count)
        self.total_rate_cap = float(total_rate_cap)
        self.prior_rate_cap = float(prior_rate_cap)
        self.boundary_scale_cap = float(boundary_scale_cap)
        self.rate_roundoff_margin = float(rate_roundoff_margin)
        self.relation_enabled = bool(relation_enabled)
        self.relation_source_scale = relation_source_scale
        self.relation_grid_size = int(relation_grid_size)
        self.relation_dim = int(relation_dim)
        self.relation_head_dim = int(relation_head_dim)
        self.relation_delta_cap = float(relation_delta_cap)
        self.atom_mass_cap = (
            (
                self.total_rate_cap
                - self.prior_rate_cap
                - self.rate_roundoff_margin
            )
            / (self.reference_count * self.boundary_scale_cap)
        )
        self.atom_mode = atom_mode
        self.heads = nn.ModuleDict(
            {
                name: PointwiseSeverityAtomHead(
                    available[name],
                    hidden_channels,
                    self.num_boundaries,
                    atom_rate_init=atom_rate_init,
                    atom_mass_cap=self.atom_mass_cap,
                    atom_mode=self.atom_mode,
                    dropout=dropout,
                )
                for name in selected
            }
        )
        self.relation_field: Optional[OrdinalPairInteractionField]
        if self.relation_enabled:
            self.relation_field = OrdinalPairInteractionField(
                available[self.relation_source_scale],
                self.num_boundaries,
                grid_size=self.relation_grid_size,
                relation_dim=self.relation_dim,
                head_dim=self.relation_head_dim,
                delta_cap=self.relation_delta_cap,
            )
        else:
            # Assigning None instead of an inert module preserves the exact v3
            # parameter/state-dict surface when relations are disabled.
            self.relation_field = None

        self.scale_simplex_logits = nn.Parameter(
            torch.zeros(len(selected), self.num_boundaries)
        )
        self.raw_boundary_scales = nn.Parameter(
            torch.full(
                (self.num_boundaries,),
                _inverse_sigmoid_fraction(
                    boundary_scale_init,
                    self.boundary_scale_cap,
                    name="boundary scale",
                ),
            )
        )
        self.raw_prior_rates = nn.Parameter(
            torch.full(
                (self.num_boundaries,),
                _inverse_sigmoid_fraction(
                    prior_rate_init,
                    self.prior_rate_cap,
                    name="prior rate",
                ),
            )
        )
        if atom_mode == "hybrid":
            mix_logit = math.log(hybrid_cumulative_init / (1.0 - hybrid_cumulative_init))
            self.atom_mix_logits = nn.Parameter(
                torch.full((self.num_boundaries,), mix_logit)
            )
        else:
            self.register_parameter("atom_mix_logits", None)

    @property
    def prior_rates(self) -> torch.Tensor:
        return self.prior_rate_cap * self.raw_prior_rates.sigmoid()

    @property
    def boundary_scales(self) -> torch.Tensor:
        return self.boundary_scale_cap * self.raw_boundary_scales.sigmoid()

    @property
    def scale_simplex(self) -> torch.Tensor:
        return self.scale_simplex_logits.softmax(dim=0)

    def _compile_atoms(self, atoms: torch.Tensor) -> torch.Tensor:
        cumulative = reverse_cumulative_atoms(atoms, dim=1)
        if self.atom_mode == "cumulative":
            return cumulative
        if self.atom_mode == "independent":
            return atoms
        if self.atom_mix_logits is None:  # pragma: no cover - constructor invariant
            raise RuntimeError("hybrid atom mode has no mixing parameters")
        mix = self.atom_mix_logits.sigmoid()[None, :, None, None]
        return mix * cumulative + (1.0 - mix) * atoms

    def forward(
        self,
        encoder_output: OriginEncoderOutput,
        *,
        force_decoder_fp64: bool = True,
        retain_encoder_output: bool = False,
    ) -> OriginOutput:
        if tuple(name for name in self.evidence_scales if name not in encoder_output.scales):
            missing = [name for name in self.evidence_scales if name not in encoder_output.scales]
            raise ValueError(f"encoder output is missing scales {missing}")

        scale_simplex = self.scale_simplex
        boundary_scales = self.boundary_scales
        _require_finite(scale_simplex, "scale simplex")
        _require_finite(boundary_scales, "boundary scales")
        scale_evidence: Dict[str, OriginScaleEvidence] = {}

        for scale_index, name in enumerate(self.evidence_scales):
            encoded: OriginEncoderScale = encoder_output.scales[name]
            features = encoded.features
            valid_mask = encoded.valid_mask
            if valid_mask.shape != features.shape[:1] + features.shape[-2:]:
                raise ValueError(f"valid mask shape mismatch at scale {name}")
            if valid_mask.dtype != torch.bool:
                valid_mask = valid_mask.bool()

            # Evidence heads are tiny relative to ConvNeXt and sit immediately
            # before the bounded atom transform and structural decoder. Keep
            # this sensitive path in FP32 even if the image trunk runs under AMP.
            with torch.autocast(device_type=features.device.type, enabled=False):
                atom_logits, atoms = self.heads[name](features.float())
                compiled = self._compile_atoms(atoms)
                original_count = valid_mask.sum(dim=(-2, -1)).to(compiled.dtype)
                geometry_weight = torch.where(
                    original_count > 0,
                    self.reference_count / original_count.clamp_min(1.0),
                    torch.zeros_like(original_count),
                )
                scale_and_boundary = (
                    scale_simplex[scale_index] * boundary_scales
                )[None, :, None, None]
                unmasked_rates = (
                    compiled
                    * scale_and_boundary
                    * geometry_weight[:, None, None, None]
                )
                local_rates = torch.where(
                    valid_mask[:, None],
                    unmasked_rates,
                    torch.zeros_like(unmasked_rates),
                )
            _require_finite(local_rates, f"local rates at {name}")
            scale_evidence[name] = OriginScaleEvidence(
                name=name,
                atom_logits=atom_logits,
                incremental_atoms=atoms,
                compiled_atoms=compiled,
                local_rate_map=local_rates,
                valid_mask=valid_mask,
                geometry_weight=geometry_weight,
                scale_weights=scale_simplex[scale_index],
                metadata=encoded.metadata,
            )

        first = scale_evidence[self.evidence_scales[0]].local_rate_map
        # Sum the stored FP32 local ledger in FP64. This makes the declared
        # roundoff reserve conservative even for the densest s4 lattice and
        # leaves the decoder on one continuous FP64 path.
        prior = self.prior_rates.to(device=first.device, dtype=_DECODER_DTYPE)
        prior = prior.unsqueeze(0).expand(first.shape[0], -1)
        base_total = sum_local_rate_maps(
            {name: item.local_rate_map for name, item in scale_evidence.items()},
            prior,
        )
        # The bounded atom transform, bounded scale, scale simplex, and
        # conserved geometry imply in exact arithmetic:
        #   total <= prior_cap + reference_count * scale_cap * atom_mass_cap
        #         = total_rate_cap - rate_roundoff_margin.
        maximum_total = float(base_total.detach().amax().item())
        if maximum_total > self.total_rate_cap:
            raise FloatingPointError(
                "ORIGIN bounded generator violated its architectural rate cap "
                f"{self.total_rate_cap:g}: {maximum_total:g}"
            )
        relation_evidence: Optional[OriginRelationEvidence] = None
        total = base_total
        if self.relation_field is not None:
            if self.relation_source_scale not in encoder_output.scales:
                raise ValueError(
                    "encoder output is missing relation source scale "
                    f"{self.relation_source_scale!r}"
                )
            # The relation trace and bounded merge are part of the structural
            # decoder, so they run outside AMP just like the local atom heads.
            source = encoder_output.scales[self.relation_source_scale]
            with torch.autocast(device_type=source.features.device.type, enabled=False):
                relation_evidence = self.relation_field(source)
                total = bounded_rate_log_odds_merge(
                    base_total,
                    relation_evidence.cumulative_log_odds,
                    total_rate_cap=self.total_rate_cap,
                )
        decoded = decode_pure_birth_rates(total, force_fp64=force_decoder_fp64)
        return _origin_output_from_decoded(
            decoded,
            scale_evidence=scale_evidence,
            prior_rates=prior,
            atom_mode=self.atom_mode,
            scale_simplex=scale_simplex,
            boundary_scales=boundary_scales,
            total_rate_cap=self.total_rate_cap,
            prior_rate_cap=self.prior_rate_cap,
            boundary_scale_cap=self.boundary_scale_cap,
            atom_mass_cap=self.atom_mass_cap,
            rate_roundoff_margin=self.rate_roundoff_margin,
            encoder_output=encoder_output if retain_encoder_output else None,
            base_total_rates=base_total,
            relation_evidence=relation_evidence,
        )


@dataclass
class OriginInterventionOutput:
    """Exact internal deletion and replay of an ORIGIN evidence ledger."""

    baseline: OriginOutput
    output: OriginOutput
    removal_masks: Dict[str, torch.Tensor]
    removed_rates: torch.Tensor

    @property
    def delta_expected_grade(self) -> torch.Tensor:
        return self.baseline.expected_grade - self.output.expected_grade

    @property
    def class_probs(self) -> torch.Tensor:
        return self.output.class_probs

    @property
    def cumulative_probs(self) -> torch.Tensor:
        return self.output.cumulative_probs

    @property
    def predicted_grade(self) -> torch.Tensor:
        return self.output.predicted_grade

    @property
    def monotone_grade(self) -> torch.Tensor:
        return self.output.posterior_median


def _canonical_removal_mask(
    removal: torch.Tensor,
    target: torch.Tensor,
    *,
    name: str,
) -> torch.Tensor:
    removal = torch.as_tensor(removal, device=target.device)
    if removal.ndim == 2:
        removal = removal.unsqueeze(0)
    if removal.ndim == 4 and removal.shape[1] == 1:
        removal = removal[:, 0]
    if removal.ndim != 3:
        raise ValueError(
            f"removal mask for {name!r} must have shape (H,W), (N,H,W), "
            "or (N,1,H,W)"
        )
    if removal.shape[0] == 1 and target.shape[0] > 1:
        removal = removal.expand(target.shape[0], -1, -1)
    if tuple(removal.shape) != tuple(target.shape):
        raise ValueError(
            f"removal mask for {name!r} has shape {tuple(removal.shape)}; "
            f"expected {tuple(target.shape)}"
        )
    return removal.bool()


def replay_without(
    output: OriginOutput,
    removal_masks: Mapping[str, torch.Tensor],
    *,
    force_decoder_fp64: bool = True,
) -> OriginInterventionOutput:
    """Delete stored local contributions and replay the same CTMC decoder.

    ``True`` means delete.  Geometry weights and the original valid masks are
    copied from ``output`` and are never recalculated.  Omitting a scale means
    delete nothing at that scale.
    """

    unknown = set(removal_masks) - set(output.scale_evidence)
    if unknown:
        raise ValueError(f"removal masks contain unknown scales {sorted(unknown)}")

    replayed: Dict[str, OriginScaleEvidence] = {}
    canonical: Dict[str, torch.Tensor] = {}
    removed_rates = torch.zeros_like(output.prior_rates)
    for name, evidence in output.scale_evidence.items():
        requested = removal_masks.get(name)
        if requested is None:
            mask = torch.zeros_like(evidence.valid_mask)
        else:
            mask = _canonical_removal_mask(
                requested, evidence.valid_mask, name=name
            )
        # Removing an already-invalid cell is a well-defined no-op.
        mask = mask & evidence.valid_mask
        canonical[name] = mask
        removed_map = torch.where(
            mask[:, None],
            evidence.local_rate_map,
            torch.zeros_like(evidence.local_rate_map),
        )
        removed_rates = removed_rates + removed_map.to(
            dtype=removed_rates.dtype
        ).sum(dim=(-2, -1))
        kept = torch.where(
            mask[:, None],
            torch.zeros_like(evidence.local_rate_map),
            evidence.local_rate_map,
        )
        replayed[name] = replace(evidence, local_rate_map=kept)

    # Sum survivors rather than renormalizing or re-running any evidence head.
    replay_base_rates = sum_local_rate_maps(
        {name: item.local_rate_map for name, item in replayed.items()},
        output.prior_rates,
    )
    replay_rates = replay_base_rates
    if output.relation_evidence is not None:
        replay_rates = bounded_rate_log_odds_merge(
            replay_base_rates,
            output.relation_evidence.cumulative_log_odds,
            total_rate_cap=output.total_rate_cap,
        )
    decoded = decode_pure_birth_rates(replay_rates, force_fp64=force_decoder_fp64)
    replay_output = _origin_output_from_decoded(
        decoded,
        scale_evidence=replayed,
        prior_rates=output.prior_rates,
        atom_mode=output.atom_mode,
        scale_simplex=output.scale_simplex,
        boundary_scales=output.boundary_scales,
        total_rate_cap=output.total_rate_cap,
        prior_rate_cap=output.prior_rate_cap,
        boundary_scale_cap=output.boundary_scale_cap,
        atom_mass_cap=output.atom_mass_cap,
        rate_roundoff_margin=output.rate_roundoff_margin,
        encoder_output=output.encoder_output,
        base_total_rates=replay_base_rates,
        relation_evidence=output.relation_evidence,
    )
    return OriginInterventionOutput(
        baseline=output,
        output=replay_output,
        removal_masks=canonical,
        removed_rates=removed_rates,
    )


@dataclass
class OriginRelationInterventionOutput:
    """Exact deletion and replay of stored cross-region pair messages."""

    baseline: OriginOutput
    output: OriginOutput
    removal_mask: torch.Tensor
    removed_edge_messages: torch.Tensor

    @property
    def delta_expected_grade(self) -> torch.Tensor:
        return self.baseline.expected_grade - self.output.expected_grade

    @property
    def delta_cumulative_log_odds(self) -> torch.Tensor:
        baseline = self.baseline.relation_evidence
        replayed = self.output.relation_evidence
        if baseline is None or replayed is None:  # pragma: no cover - invariant
            raise RuntimeError("relation intervention is missing its stored trace")
        return baseline.cumulative_log_odds - replayed.cumulative_log_odds

    @property
    def class_probs(self) -> torch.Tensor:
        return self.output.class_probs

    @property
    def predicted_grade(self) -> torch.Tensor:
        return self.output.predicted_grade


def _canonical_relation_removal_mask(
    removal: torch.Tensor,
    target: torch.Tensor,
) -> torch.Tensor:
    """Broadcast an unambiguous relation mask to ``(N,K-1,M,M)``.

    Two-dimensional masks apply to every sample and boundary.  A
    three-dimensional mask is *only* sample-specific ``(N,M,M)``.  Callers
    selecting boundaries must supply an explicit four-dimensional mask such
    as ``(1,K-1,M,M)`` or ``(N,K-1,M,M)``.
    """

    removal = torch.as_tensor(removal, device=target.device)
    if target.ndim != 4 or target.shape[-1] != target.shape[-2]:
        raise ValueError("relation target must have shape (N,K-1,M,M)")
    batch, boundaries, regions, _ = target.shape
    if tuple(removal.shape[-2:]) != (regions, regions):
        raise ValueError(
            "relation removal endpoint dimensions must match the stored "
            f"lattice {(regions, regions)}; got {tuple(removal.shape[-2:])}"
        )
    if removal.ndim == 2:
        removal = removal[None, None]
    elif removal.ndim == 3:
        if removal.shape[0] != batch:
            raise ValueError(
                "three-dimensional relation masks are sample-specific and "
                f"must have shape (N,M,M) with N={batch}; boundary-specific "
                "masks must be explicitly four-dimensional"
            )
        removal = removal[:, None]
    elif removal.ndim != 4:
        raise ValueError(
            "relation removal mask must have shape (M,M), (N,M,M), "
            "(1,K-1,M,M), or (N,K-1,M,M)"
        )
    if removal.shape[0] not in (1, batch) or removal.shape[1] not in (1, boundaries):
        raise ValueError(
            "relation removal batch/boundary dimensions are not broadcastable "
            f"to {(batch, boundaries)}; got {tuple(removal.shape[:2])}"
        )
    return removal.bool().expand(batch, boundaries, regions, regions)


def replay_without_relations(
    output: OriginOutput,
    edge_removal_mask: torch.Tensor,
    *,
    force_decoder_fp64: bool = True,
) -> OriginRelationInterventionOutput:
    """Delete stored pair messages and replay the bounded ordinal generator.

    No feature map, attention gate, or encoder activation is recomputed.  The
    fixed v3 local ledger is merged with the cumulative field compiled from
    the surviving stored edge messages, so the reported counterfactual is an
    exact intervention in the prediction path rather than a visualization.
    """

    relation = output.relation_evidence
    if relation is None:
        raise ValueError("output does not contain relational evidence")
    if output.base_total_rates is None:
        raise ValueError("relation-enabled output is missing its base rate ledger")
    canonical = _canonical_relation_removal_mask(
        edge_removal_mask, relation.edge_messages
    )
    canonical = canonical & relation.edge_valid_mask[:, None]
    removed = torch.where(
        canonical, relation.edge_messages, torch.zeros_like(relation.edge_messages)
    )
    kept = torch.where(
        canonical, torch.zeros_like(relation.edge_messages), relation.edge_messages
    )
    target_incremental, incremental, cumulative = aggregate_ordinal_pair_messages(
        kept,
        relation.edge_valid_mask,
        relation.region_valid_mask,
        delta_cap=relation.delta_cap,
    )
    replay_relation = replace(
        relation,
        edge_messages=kept,
        target_incremental_log_odds=target_incremental,
        incremental_log_odds=incremental,
        cumulative_log_odds=cumulative,
    )
    replay_rates = bounded_rate_log_odds_merge(
        output.base_total_rates,
        cumulative,
        total_rate_cap=output.total_rate_cap,
    )
    decoded = decode_pure_birth_rates(
        replay_rates, force_fp64=force_decoder_fp64
    )
    replay_output = _origin_output_from_decoded(
        decoded,
        scale_evidence=output.scale_evidence,
        prior_rates=output.prior_rates,
        atom_mode=output.atom_mode,
        scale_simplex=output.scale_simplex,
        boundary_scales=output.boundary_scales,
        total_rate_cap=output.total_rate_cap,
        prior_rate_cap=output.prior_rate_cap,
        boundary_scale_cap=output.boundary_scale_cap,
        atom_mass_cap=output.atom_mass_cap,
        rate_roundoff_margin=output.rate_roundoff_margin,
        encoder_output=output.encoder_output,
        base_total_rates=output.base_total_rates,
        relation_evidence=replay_relation,
    )
    return OriginRelationInterventionOutput(
        baseline=output,
        output=replay_output,
        removal_mask=canonical,
        removed_edge_messages=removed,
    )


@dataclass
class TopKOriginInterventionReport:
    """Top-k boundary witnesses and their exact all-boundary removal effect."""

    boundary: int
    k: int
    selected_flat_indices: torch.Tensor
    selected_boundary_rates: torch.Tensor
    scale_offsets: Dict[str, Tuple[int, int]]
    intervention: OriginInterventionOutput


def topk_rate_intervention(
    output: OriginOutput,
    *,
    boundary: int,
    k: int,
    force_decoder_fp64: bool = True,
) -> TopKOriginInterventionReport:
    """Remove the k largest valid local witnesses for one boundary exactly."""

    num_boundaries = output.total_rates.shape[-1]
    if not 0 <= boundary < num_boundaries:
        raise ValueError(f"boundary must lie in [0, {num_boundaries - 1}]")
    if k < 1:
        raise ValueError("k must be positive")

    score_parts = []
    valid_parts = []
    offsets: Dict[str, Tuple[int, int]] = {}
    cursor = 0
    for name, evidence in output.scale_evidence.items():
        scores = evidence.local_rate_map[:, boundary].flatten(1)
        valid = evidence.valid_mask.flatten(1)
        score_parts.append(scores)
        valid_parts.append(valid)
        offsets[name] = (cursor, cursor + scores.shape[1])
        cursor += scores.shape[1]
    scores = torch.cat(score_parts, dim=1)
    valid = torch.cat(valid_parts, dim=1)
    if bool((valid.sum(dim=1) < k).any()):
        raise ValueError("k exceeds the valid evidence-cell count for a sample")
    ranked_scores = scores.masked_fill(~valid, -torch.inf)
    selected_scores, selected = ranked_scores.topk(k, dim=1)

    removals: Dict[str, torch.Tensor] = {}
    for name, evidence in output.scale_evidence.items():
        start, stop = offsets[name]
        flat_counts = torch.zeros_like(
            evidence.valid_mask.flatten(1), dtype=torch.int64
        )
        within = (selected >= start) & (selected < stop)
        local = (selected - start).clamp(0, stop - start - 1)
        # scatter_ can let a later false/clamped entry overwrite an earlier
        # true entry at index zero. Integer scatter-add has union semantics.
        flat_counts.scatter_add_(1, local, within.to(torch.int64))
        removals[name] = (flat_counts > 0).reshape_as(evidence.valid_mask)

    intervention = replay_without(
        output, removals, force_decoder_fp64=force_decoder_fp64
    )
    return TopKOriginInterventionReport(
        boundary=boundary,
        k=k,
        selected_flat_indices=selected,
        selected_boundary_rates=selected_scores,
        scale_offsets=offsets,
        intervention=intervention,
    )


class OriginModel(nn.Module):
    """Image-to-grade ORIGIN model with an auditable local evidence ledger."""

    def __init__(
        self,
        *,
        num_classes: int = 5,
        encoder_name: str = "convnext_tiny",
        pretrained: bool = True,
        evidence_scales: Sequence[str] = ("s4", "s8", "s16", "s32"),
        projection_dim: int = 128,
        reference_count: float = 4096.0,
        atom_mode: str = "cumulative",
        hybrid_cumulative_init: float = 0.9,
        atom_rate_init: float = 1e-6,
        prior_rate_init: float = 1e-4,
        boundary_scale_init: float = 1.0,
        total_rate_cap: float = 64.0,
        prior_rate_cap: float = 1.0,
        boundary_scale_cap: float = 2.0,
        rate_roundoff_margin: float = 1.0,
        evidence_dropout: float = 0.0,
        mask_valid_fraction: float = 0.5,
        grad_checkpoint: bool = False,
        relation_enabled: bool = False,
        relation_source_scale: str = "s8",
        relation_grid_size: int = 10,
        relation_dim: int = 64,
        relation_head_dim: int = 16,
        relation_delta_cap: float = 2.0,
        encoder: Optional[nn.Module] = None,
    ) -> None:
        super().__init__()
        encoder_name = str(encoder_name).lower()
        if encoder_name not in {"convnext_tiny", "convnext_tiny_srff"}:
            raise ValueError(
                "ORIGIN supports encoder_name='convnext_tiny' or "
                "'convnext_tiny_srff'"
            )
        if encoder is None:
            encoder_class = (
                ConvNeXtTinySRFFEncoder
                if encoder_name == "convnext_tiny_srff"
                else ConvNeXtTinyPyramidEncoder
            )
            encoder = encoder_class(
                pretrained=pretrained,
                grad_checkpoint=grad_checkpoint,
                mask_valid_fraction=mask_valid_fraction,
            )
        if not hasattr(encoder, "STAGE_CHANNELS"):
            raise TypeError("encoder must expose a STAGE_CHANNELS mapping")
        self.encoder = encoder
        self.num_classes = int(num_classes)
        self.encoder_name = encoder_name
        self.generator = ConservedOrdinalGenerator(
            stage_channels=encoder.STAGE_CHANNELS,
            num_classes=num_classes,
            hidden_channels=projection_dim,
            evidence_scales=evidence_scales,
            reference_count=reference_count,
            atom_mode=atom_mode,
            hybrid_cumulative_init=hybrid_cumulative_init,
            atom_rate_init=atom_rate_init,
            prior_rate_init=prior_rate_init,
            boundary_scale_init=boundary_scale_init,
            total_rate_cap=total_rate_cap,
            prior_rate_cap=prior_rate_cap,
            boundary_scale_cap=boundary_scale_cap,
            rate_roundoff_margin=rate_roundoff_margin,
            dropout=evidence_dropout,
            relation_enabled=relation_enabled,
            relation_source_scale=relation_source_scale,
            relation_grid_size=relation_grid_size,
            relation_dim=relation_dim,
            relation_head_dim=relation_head_dim,
            relation_delta_cap=relation_delta_cap,
        )

    @property
    def evidence_scales(self) -> Tuple[str, ...]:
        return self.generator.evidence_scales

    def architecture_metadata(self) -> Dict[str, object]:
        """Serializable declaration recorded beside every checkpoint."""

        rate_parameterization = (
            "bounded_independent_sigmoid_v1"
            if self.generator.atom_mode == "independent"
            else "bounded_null_simplex_v1"
        )
        spatial_contract_factory = getattr(self.encoder, "spatial_contract", None)
        encoder_spatial_contract = (
            spatial_contract_factory()
            if callable(spatial_contract_factory)
            else {
                "kind": "native_convnext_pyramid_v1",
                "source_masking_inside_trunk": False,
            }
        )
        receptive_fields = {
            "s4": 76,
            "s8": 224,
            "s16": 1096,
            "s32": 1688,
            "s128": 344,
        }
        selected_receptive_fields = [
            receptive_fields[name]
            for name in self.evidence_scales
            if name in receptive_fields
        ]
        is_srff = self.encoder_name == "convnext_tiny_srff"
        relation_field = self.generator.relation_field
        relation_contract: Optional[Dict[str, object]] = None
        if relation_field is not None:
            relation_contract = {
                "kind": "cumulative_ordinal_pair_rate_log_odds_v1",
                "source_scale": self.generator.relation_source_scale,
                "grid_size": relation_field.grid_size,
                "num_regions": relation_field.grid_size ** 2,
                "relation_dim": relation_field.relation_dim,
                "head_dim": relation_field.head_dim,
                "delta_cap": relation_field.delta_cap,
                "merge": "C*sigmoid(log(lambda)-log(C-lambda)+D)",
                "incremental_compilation": "geometry_normalized_signed_pair_messages",
                "ordinal_compilation": "reverse_cumulative_incremental_field",
                "pair_normalization": "no_feature_dependent_global_denominator",
                "zero_initialization": "exact_v3_function_identity",
                "relation_replay": "stored_pair_message_deletion_without_reencoding",
                "no_classifier_bypass": True,
            }
        return {
            "name": "ORIGIN",
            "encoder": self.encoder_name,
            "encoder_spatial_contract": encoder_spatial_contract,
            "evidence_dependency_policy": (
                "spatial_receptive_field_firewall_v1"
                if is_srff
                else "native_convnext_stage_receptive_fields"
            ),
            "srff_window_cells": (
                ConvNeXtTinySRFFEncoder.WINDOW_CELLS if is_srff else None
            ),
            "sealed_source_masking": True if is_srff else None,
            "max_evidence_receptive_field": (
                max(selected_receptive_fields) if selected_receptive_fields else None
            ),
            "num_classes": self.num_classes,
            "evidence_scales": list(self.evidence_scales),
            "atom_mode": self.generator.atom_mode,
            "reference_count": self.generator.reference_count,
            "rate_parameterization": rate_parameterization,
            "total_rate_cap": self.generator.total_rate_cap,
            "prior_rate_cap": self.generator.prior_rate_cap,
            "boundary_scale_cap": self.generator.boundary_scale_cap,
            "atom_mass_cap": self.generator.atom_mass_cap,
            "rate_roundoff_margin": self.generator.rate_roundoff_margin,
            "decoder": "fp64_taylor24_scaled_squared_pure_birth_exponential",
            "available_decisions": [
                "posterior_median",
                "class_map",
                "rounded_expected",
            ],
            "model_default_decision": "class_map",
            "run_decision_owned_by_trainer_config": True,
            "local_rate_layout": "NHW(K-1)",
            "no_classifier_bypass": True,
            "intervention": "stored_local_rate_subtraction_without_renormalization",
            "relation_enabled": relation_field is not None,
            "relation_contract": relation_contract,
            "relation_intervention": (
                "stored_pair_message_deletion_then_exact_bounded_rate_replay"
                if relation_field is not None
                else None
            ),
        }

    def forward(
        self,
        images: torch.Tensor,
        pixel_valid_mask: Optional[torch.Tensor] = None,
        *,
        force_decoder_fp64: bool = True,
        return_encoder_maps: bool = False,
    ) -> OriginOutput:
        encoded = self.encoder(images, pixel_valid_mask)
        return self.generator(
            encoded,
            force_decoder_fp64=force_decoder_fp64,
            retain_encoder_output=return_encoder_maps,
        )

    def replay_without(
        self,
        output: OriginOutput,
        removal_masks: Mapping[str, torch.Tensor],
        *,
        force_decoder_fp64: bool = True,
    ) -> OriginInterventionOutput:
        return replay_without(
            output,
            removal_masks,
            force_decoder_fp64=force_decoder_fp64,
        )

    def topk_intervention(
        self,
        output: OriginOutput,
        *,
        boundary: int,
        k: int,
        force_decoder_fp64: bool = True,
    ) -> TopKOriginInterventionReport:
        return topk_rate_intervention(
            output,
            boundary=boundary,
            k=k,
            force_decoder_fp64=force_decoder_fp64,
        )

    def replay_without_relations(
        self,
        output: OriginOutput,
        edge_removal_mask: torch.Tensor,
        *,
        force_decoder_fp64: bool = True,
    ) -> OriginRelationInterventionOutput:
        return replay_without_relations(
            output,
            edge_removal_mask,
            force_decoder_fp64=force_decoder_fp64,
        )


def build_origin_model(**kwargs) -> OriginModel:
    """Stable construction hook for training and evaluation entry points."""

    return OriginModel(**kwargs)


__all__ = [
    "aggregate_ordinal_pair_messages",
    "bounded_rate_log_odds_merge",
    "ChannelLayerNorm2d",
    "ConservedOrdinalGenerator",
    "OriginDecodedDistribution",
    "OriginInterventionOutput",
    "OriginModel",
    "OriginOutput",
    "OriginRelationEvidence",
    "OriginRelationInterventionOutput",
    "OriginScaleEvidence",
    "OrdinalPairInteractionField",
    "PointwiseSeverityAtomHead",
    "TopKOriginInterventionReport",
    "build_origin_model",
    "decode_pure_birth_rates",
    "fit_pure_birth_rates",
    "pure_birth_generator",
    "replay_without",
    "replay_without_relations",
    "reverse_cumulative_atoms",
    "sum_local_rate_maps",
    "topk_rate_intervention",
]
