"""ORIGIN: an ordinal grade generated by conserved local transition rates.

The model has one prediction path.  Spatial cells emit non-negative evidence
for adjacent ordinal transitions, those contributions add to a conservative
pure-birth generator, and the endpoint distribution of that generator is the
grade distribution.  There is no pooled classifier, residual logit, or other
route around the reported local ledger.

The generator is useful beyond retinal grading, but the structural prior is
specifically ordinal: a severity atom at level ``m`` can support every
prerequisite transition ``k <= m``.  ``atom_mode='independent'`` is retained
as a matched ablation; ``'hybrid'`` learns how strongly to impose that prior.

Rates are latent evidence-transition rates at a fixed unit endpoint.  They are
not estimates of biological time or longitudinal disease progression.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
import math
from typing import Dict, Mapping, Optional, Sequence, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F

from .origin_encoder import (
    ConvNeXtTinyPyramidEncoder,
    ConvNeXtTinySRFFEncoder,
    OriginEncoderOutput,
    OriginEncoderScale,
    OriginScaleMetadata,
)


_ATOM_MODES = frozenset(("cumulative", "independent", "hybrid"))
_DECODER_DTYPE = torch.float64
_EXP_TAYLOR_DEGREE = 24
_EXP_SCALING_THETA = 0.5
_MAX_DECODER_RATE = 700.0


def _require_finite(tensor: torch.Tensor, name: str) -> None:
    if not torch.isfinite(tensor).all():
        nan = int(torch.isnan(tensor).sum().item())
        pos = int(torch.isposinf(tensor).sum().item())
        neg = int(torch.isneginf(tensor).sum().item())
        raise FloatingPointError(
            f"{name} contains non-finite values "
            f"(nan={nan}, +inf={pos}, -inf={neg})"
        )


def _inverse_sigmoid_fraction(value: float, maximum: float, *, name: str) -> float:
    """Return the logit whose bounded sigmoid equals ``value``.

    Keeping bounded parameter initialisation explicit avoids silently changing
    ORIGIN's near-null starting law when replacing the former unbounded
    softplus parameterisation.
    """

    value = float(value)
    maximum = float(maximum)
    if not math.isfinite(maximum) or maximum <= 0.0:
        raise ValueError(f"{name} maximum must be finite and positive")
    if not math.isfinite(value) or not 0.0 < value < maximum:
        raise ValueError(f"{name} initialization must lie strictly in (0, maximum)")
    return math.log(value) - math.log(maximum - value)


def reverse_cumulative_atoms(atoms: torch.Tensor, *, dim: int = 1) -> torch.Tensor:
    """Compile incremental severity atoms into prerequisite evidence."""

    if atoms.ndim == 0:
        raise ValueError("atoms must have at least one dimension")
    if atoms.shape[dim] < 1:
        raise ValueError("the atom dimension must be non-empty")
    return atoms.flip((dim,)).cumsum(dim=dim).flip((dim,))


def pure_birth_generator(rates: torch.Tensor) -> torch.Tensor:
    """Construct a conservative upper-bidiagonal CTMC generator.

    Args:
        rates: Non-negative tensor with final dimension ``K-1``.

    Returns:
        Tensor with shape ``rates.shape[:-1] + (K, K)``.  Rows sum to zero,
        off-diagonal entries are non-negative, and state ``K-1`` is absorbing.
    """

    if rates.ndim < 1 or rates.shape[-1] < 1:
        raise ValueError("rates must have shape (..., K-1) with K >= 2")
    if not rates.is_floating_point():
        raise TypeError("rates must be floating point")
    _require_finite(rates, "pure-birth rates")
    if bool((rates < 0).any()):
        raise ValueError("pure-birth rates must be non-negative")

    zeros = torch.zeros_like(rates[..., :1])
    diagonal = torch.cat((-rates, zeros), dim=-1)
    return torch.diag_embed(diagonal) + torch.diag_embed(rates, offset=1)


def _stable_matrix_exp(matrix: torch.Tensor) -> torch.Tensor:
    """Evaluate a small matrix exponential using elementary FP64 operations.

    ``torch.matrix_exp`` has an accurate forward pass for ORIGIN's generator,
    but its generic backward can be catastrophically inaccurate for the
    highly non-normal, unequal-rate upper-bidiagonal matrices encountered in
    training.  This implementation first scales every matrix in the batch so
    its infinity norm is at most 0.5, evaluates the degree-24 Taylor series,
    and then squares back to the requested scale.  Autograd therefore sees
    only additions and matrix multiplications.  The Taylor remainder at the
    scaled norm is below FP64 roundoff for this decoder.

    The integer scaling choice is made from a detached norm.  It changes only
    the numerical evaluation graph, not the represented matrix exponential.
    """

    if matrix.ndim < 2 or matrix.shape[-1] != matrix.shape[-2]:
        raise ValueError("matrix must have shape (..., K, K)")
    if matrix.dtype != _DECODER_DTYPE:
        raise TypeError("the stable matrix exponential requires FP64 input")
    _require_finite(matrix, "stable matrix-exponential input")

    norm = matrix.detach().abs().sum(dim=-1).amax()
    norm_value = float(norm.item())
    if norm_value <= _EXP_SCALING_THETA:
        squarings = 0
    else:
        squarings = int(
            math.ceil(math.log2(norm_value / _EXP_SCALING_THETA))
        )
    scale = math.ldexp(1.0, squarings)
    scaled = matrix / scale

    size = matrix.shape[-1]
    identity = torch.eye(size, dtype=matrix.dtype, device=matrix.device)
    identity = identity.expand(matrix.shape[:-2] + (size, size))
    result = identity
    term = identity
    for order in range(1, _EXP_TAYLOR_DEGREE + 1):
        term = torch.matmul(term, scaled) / float(order)
        result = result + term
    for _ in range(squarings):
        result = torch.matmul(result, result)
    return result


@dataclass
class OriginDecodedDistribution:
    """Endpoint law produced by a pure-birth ordinal generator."""

    total_rates: torch.Tensor
    generator: torch.Tensor
    transition_matrix: torch.Tensor
    class_probs: torch.Tensor
    log_class_probs: torch.Tensor
    cumulative_probs: torch.Tensor
    expected_grade: torch.Tensor
    posterior_median: torch.Tensor
    class_map: torch.Tensor

    @property
    def predicted_grade(self) -> torch.Tensor:
        """Accuracy-oriented public default; explicit alternatives are stored."""

        return self.class_map

    @property
    def monotone_grade(self) -> torch.Tensor:
        """Posterior-median decision with monotone rate interventions."""

        return self.posterior_median

    # Explicit aliases make the object easy to consume beside older trainers.
    @property
    def class_probabilities(self) -> torch.Tensor:
        return self.class_probs

    @property
    def log_class_probabilities(self) -> torch.Tensor:
        return self.log_class_probs

    @property
    def cumulative_probabilities(self) -> torch.Tensor:
        return self.cumulative_probs


def decode_pure_birth_rates(
    rates: torch.Tensor,
    *,
    force_fp64: bool = True,
    probability_tolerance: float = 5e-12,
) -> OriginDecodedDistribution:
    """Evolve a unit-time pure-birth chain from grade zero.

    The structural decoder is always evaluated in FP64 with an audited Taylor
    scaling-and-squaring exponential.  This is an invariant, not a tunable
    precision option: generic matrix-exponential backward kernels can return
    incorrect gradients for ORIGIN's high, unequal transition rates.  The
    source rate ledger is retained in its original dtype while the generator,
    posterior, and log posterior remain FP64 through the training loss.
    """

    if not math.isfinite(probability_tolerance) or probability_tolerance < 0:
        raise ValueError("probability_tolerance must be finite and non-negative")
    if not force_fp64:
        raise ValueError("ORIGIN's structural decoder must run in FP64")
    if rates.ndim < 1 or rates.shape[-1] < 1 or rates.numel() < 1:
        raise ValueError("rates must have non-empty shape (..., K-1) with K >= 2")
    if not rates.is_floating_point():
        raise TypeError("rates must be floating point")
    _require_finite(rates, "pure-birth rates")
    if bool((rates < 0).any()):
        raise ValueError("pure-birth rates must be non-negative")
    maximum_rate = float(rates.detach().amax().item())
    if maximum_rate > _MAX_DECODER_RATE:
        raise FloatingPointError(
            "pure-birth rate exceeds the audited FP64 decoder range "
            f"[0, {_MAX_DECODER_RATE:g}]: {maximum_rate:g}"
        )
    decoder_rates = rates.to(dtype=_DECODER_DTYPE)
    generator = pure_birth_generator(decoder_rates)

    # Disable any outer autocast region. Probabilities and their logs must stay
    # FP64; exp(-141), already seen in a run, underflows in FP32.
    device_type = generator.device.type
    with torch.autocast(device_type=device_type, enabled=False):
        transition = _stable_matrix_exp(generator)
    _require_finite(transition, "pure-birth transition matrix")

    probabilities = transition[..., 0, :]
    if bool((probabilities < 0.0).any()):
        minimum = float(probabilities.min().item())
        raise FloatingPointError(
            "stable matrix exponential produced a negative probability "
            f"({minimum})"
        )
    # Do not clamp or renormalize the posterior. Either operation could hide a
    # catastrophic relative error in a clinically rare class and would modify
    # the exact generator law and its intervention derivatives.
    row_error = (probabilities.sum(dim=-1) - 1.0).abs()
    if bool((row_error > probability_tolerance).any()):
        maximum_error = float(row_error.max().item())
        raise FloatingPointError(
            "stable matrix exponential violated probability conservation "
            f"(maximum row-sum error={maximum_error:g})"
        )
    _require_finite(probabilities, "pure-birth class probabilities")

    cumulative = probabilities[..., 1:].flip((-1,)).cumsum(dim=-1).flip((-1,))
    grade_axis = torch.arange(
        probabilities.shape[-1],
        device=probabilities.device,
        dtype=probabilities.dtype,
    )
    expected = (probabilities * grade_axis).sum(dim=-1)
    median = (cumulative >= 0.5).sum(dim=-1)
    class_map = probabilities.argmax(dim=-1)
    tiny = torch.finfo(probabilities.dtype).tiny
    log_probabilities = probabilities.clamp_min(tiny).log()

    return OriginDecodedDistribution(
        total_rates=rates,
        generator=generator,
        transition_matrix=transition,
        class_probs=probabilities,
        log_class_probs=log_probabilities,
        cumulative_probs=cumulative,
        expected_grade=expected,
        posterior_median=median,
        class_map=class_map,
    )


def fit_pure_birth_rates(
    class_probs: torch.Tensor | Sequence[float],
    *,
    tolerance: float = 1e-10,
    max_iterations: int = 160,
    maximum_rate: float = _MAX_DECODER_RATE,
) -> torch.Tensor:
    """Invert one interior categorical law into unit-time birth rates.

    This is a mathematical/diagnostic helper, not ORIGIN's default prior
    initialization.  Image evidence only increases rates, so initializing the
    model's null prior to an imbalanced population law would prevent normal
    images from becoming highly confident grade zero.

    The first rate is ``-log(p_0)``.  Each later rate is found by bisection:
    with earlier rates fixed, endpoint mass in the current state decreases
    continuously from the remaining tail mass to zero as that rate grows.
    """

    probabilities = torch.as_tensor(class_probs, dtype=torch.float64)
    if probabilities.ndim != 1 or probabilities.numel() < 2:
        raise ValueError("class_probs must be a one-dimensional K>=2 vector")
    _require_finite(probabilities, "target class probabilities")
    if bool((probabilities <= 0).any()):
        raise ValueError("all target class probabilities must be strictly positive")
    if not math.isfinite(tolerance) or tolerance <= 0:
        raise ValueError("tolerance must be finite and positive")
    if max_iterations < 1:
        raise ValueError("max_iterations must be positive")
    if not math.isfinite(maximum_rate) or maximum_rate <= 0:
        raise ValueError("maximum_rate must be finite and positive")

    probabilities = probabilities / probabilities.sum()
    boundaries = probabilities.numel() - 1
    rates = torch.zeros(boundaries, dtype=torch.float64)
    rates[0] = -probabilities[0].log()

    for state in range(1, boundaries):
        target = float(probabilities[state].item())
        low = 0.0
        high = max(1.0, float(rates[:state].max().item()))

        def state_probability(candidate: float) -> float:
            trial = rates.clone()
            trial[state] = candidate
            decoded = decode_pure_birth_rates(trial, force_fp64=True)
            return float(decoded.class_probs[state].item())

        while state_probability(high) > target and high < maximum_rate:
            high = min(maximum_rate, high * 2.0)
        if state_probability(high) > target:
            raise RuntimeError(
                f"failed to bracket rate {state} below maximum_rate={maximum_rate}"
            )
        for _ in range(max_iterations):
            middle = (low + high) / 2.0
            value = state_probability(middle)
            if abs(value - target) <= tolerance:
                low = high = middle
                break
            if value > target:
                low = middle
            else:
                high = middle
        rates[state] = (low + high) / 2.0
    return rates


class ChannelLayerNorm2d(nn.Module):
    """LayerNorm over channels independently at every spatial cell."""

    def __init__(self, channels: int, eps: float = 1e-6) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.ones(channels))
        self.bias = nn.Parameter(torch.zeros(channels))
        self.eps = float(eps)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x.permute(0, 2, 3, 1)
        x = F.layer_norm(x, (x.shape[-1],), self.weight, self.bias, self.eps)
        return x.permute(0, 3, 1, 2).contiguous()


class PointwiseSeverityAtomHead(nn.Module):
    """A channel-only MLP that emits a bounded local severity measure.

    In cumulative/hybrid modes, each cell distributes a fixed finite mass
    budget between the ordinal severity atoms and an explicit null atom. In
    the matched independent ablation, each boundary instead receives its own
    bounded sigmoid atom so boundaries do not compete. Both constructions are
    non-negative and guarantee the per-boundary ``atom_mass_cap`` used by the
    generator's proof-level rate bound.
    """

    def __init__(
        self,
        in_channels: int,
        hidden_channels: int,
        num_boundaries: int,
        *,
        atom_rate_init: float = 1e-4,
        atom_mass_cap: float = 1.0,
        atom_mode: str = "cumulative",
        dropout: float = 0.0,
    ) -> None:
        super().__init__()
        if min(in_channels, hidden_channels, num_boundaries) < 1:
            raise ValueError("head dimensions must be positive")
        if not 0.0 <= dropout < 1.0:
            raise ValueError("dropout must lie in [0, 1)")
        if not math.isfinite(atom_mass_cap) or atom_mass_cap <= 0.0:
            raise ValueError("atom_mass_cap must be finite and positive")
        atom_mode = str(atom_mode).lower()
        if atom_mode not in _ATOM_MODES:
            raise ValueError(f"atom_mode must be one of {sorted(_ATOM_MODES)}")
        initial_fraction = float(atom_rate_init) / float(atom_mass_cap)
        active_multiplicity = 1 if atom_mode == "independent" else num_boundaries
        null_fraction = 1.0 - active_multiplicity * initial_fraction
        if (
            not math.isfinite(initial_fraction)
            or initial_fraction <= 0.0
            or null_fraction <= 0.0
        ):
            raise ValueError(
                "atom_rate_init must be positive and leave non-zero null mass "
                "inside atom_mass_cap"
            )
        self.num_boundaries = int(num_boundaries)
        self.atom_mass_cap = float(atom_mass_cap)
        self.atom_mode = atom_mode
        self.projection = nn.Conv2d(in_channels, hidden_channels, 1)
        self.norm = ChannelLayerNorm2d(hidden_channels)
        self.activation = nn.GELU()
        self.dropout = nn.Dropout2d(dropout)
        self.atom_logits = nn.Conv2d(hidden_channels, num_boundaries, 1)
        nn.init.normal_(self.atom_logits.weight, mean=0.0, std=0.01)
        # For cumulative/hybrid modes, equal active logits b and a fixed null
        # logit zero give q_active/q_null=exp(b). For the independent ablation,
        # the same expression is the inverse sigmoid of each uncoupled atom.
        initial_logit = math.log(initial_fraction / null_fraction)
        nn.init.constant_(self.atom_logits.bias, initial_logit)

    def forward(self, features: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        if features.ndim != 4:
            raise ValueError("features must have shape (N,C,H,W)")
        x = self.projection(features)
        x = self.dropout(self.activation(self.norm(x)))
        logits = self.atom_logits(x)
        _require_finite(logits, "severity atom logits")
        if self.atom_mode == "independent":
            # Preserve a genuinely independent matched ablation: changing one
            # boundary atom does not suppress another through a shared simplex.
            atoms = logits.sigmoid() * self.atom_mass_cap
        else:
            null_logits = torch.zeros_like(logits[:, :1])
            atom_probabilities = torch.cat((logits, null_logits), dim=1).softmax(dim=1)
            atoms = atom_probabilities[:, : self.num_boundaries] * self.atom_mass_cap
        _require_finite(atoms, "severity atoms")
        return logits, atoms


@dataclass
class OriginScaleEvidence:
    """Replayable evidence ledger for one spatial scale."""

    name: str
    atom_logits: torch.Tensor
    incremental_atoms: torch.Tensor
    compiled_atoms: torch.Tensor
    local_rate_map: torch.Tensor
    valid_mask: torch.Tensor
    geometry_weight: torch.Tensor
    scale_weights: torch.Tensor
    metadata: OriginScaleMetadata

    @property
    def rate_contributions(self) -> torch.Tensor:
        return self.local_rate_map


@dataclass
class OriginOutput:
    """Complete prediction trace; all grade probabilities derive from ledger."""

    scale_evidence: Dict[str, OriginScaleEvidence]
    prior_rates: torch.Tensor
    total_rates: torch.Tensor
    generator: torch.Tensor
    transition_matrix: torch.Tensor
    class_probs: torch.Tensor
    log_class_probs: torch.Tensor
    cumulative_probs: torch.Tensor
    expected_grade: torch.Tensor
    posterior_median: torch.Tensor
    class_map: torch.Tensor
    atom_mode: str
    scale_simplex: torch.Tensor
    boundary_scales: torch.Tensor
    total_rate_cap: float
    prior_rate_cap: float
    boundary_scale_cap: float
    atom_mass_cap: float
    rate_roundoff_margin: float
    encoder_output: Optional[OriginEncoderOutput] = None

    @property
    def local_rate_maps(self) -> Dict[str, torch.Tensor]:
        """Local rate ledgers in spatial-first ``(N,H,W,K-1)`` layout."""

        return {
            name: evidence.local_rate_map.permute(0, 2, 3, 1)
            for name, evidence in self.scale_evidence.items()
        }

    @property
    def local_rate_maps_channels_first(self) -> Dict[str, torch.Tensor]:
        """Internal convolution-layout views with shape ``(N,K-1,H,W)``."""

        return {
            name: evidence.local_rate_map
            for name, evidence in self.scale_evidence.items()
        }

    @property
    def valid_masks(self) -> Dict[str, torch.Tensor]:
        return {
            name: evidence.valid_mask
            for name, evidence in self.scale_evidence.items()
        }

    @property
    def metadata(self) -> Dict[str, OriginScaleMetadata]:
        return {
            name: evidence.metadata
            for name, evidence in self.scale_evidence.items()
        }

    @property
    def predicted_grade(self) -> torch.Tensor:
        return self.class_map

    @property
    def monotone_grade(self) -> torch.Tensor:
        return self.posterior_median

    @property
    def class_probabilities(self) -> torch.Tensor:
        return self.class_probs

    @property
    def log_class_probabilities(self) -> torch.Tensor:
        return self.log_class_probs

    @property
    def cumulative_probabilities(self) -> torch.Tensor:
        return self.cumulative_probs


def _origin_output_from_decoded(
    decoded: OriginDecodedDistribution,
    *,
    scale_evidence: Dict[str, OriginScaleEvidence],
    prior_rates: torch.Tensor,
    atom_mode: str,
    scale_simplex: torch.Tensor,
    boundary_scales: torch.Tensor,
    total_rate_cap: float,
    prior_rate_cap: float,
    boundary_scale_cap: float,
    atom_mass_cap: float,
    rate_roundoff_margin: float,
    encoder_output: Optional[OriginEncoderOutput],
) -> OriginOutput:
    return OriginOutput(
        scale_evidence=scale_evidence,
        prior_rates=prior_rates,
        total_rates=decoded.total_rates,
        generator=decoded.generator,
        transition_matrix=decoded.transition_matrix,
        class_probs=decoded.class_probs,
        log_class_probs=decoded.log_class_probs,
        cumulative_probs=decoded.cumulative_probs,
        expected_grade=decoded.expected_grade,
        posterior_median=decoded.posterior_median,
        class_map=decoded.class_map,
        atom_mode=atom_mode,
        scale_simplex=scale_simplex,
        boundary_scales=boundary_scales,
        total_rate_cap=total_rate_cap,
        prior_rate_cap=prior_rate_cap,
        boundary_scale_cap=boundary_scale_cap,
        atom_mass_cap=atom_mass_cap,
        rate_roundoff_margin=rate_roundoff_margin,
        encoder_output=encoder_output,
    )


def sum_local_rate_maps(
    local_rate_maps: Mapping[str, torch.Tensor],
    prior_rates: torch.Tensor,
) -> torch.Tensor:
    """Conserve all local contributions into one boundary-rate vector."""

    if not local_rate_maps:
        raise ValueError("at least one local rate map is required")
    result = prior_rates
    for name, rate_map in local_rate_maps.items():
        if rate_map.ndim != 4:
            raise ValueError(
                f"local rate map {name!r} must have shape (N,K-1,H,W)"
            )
        if tuple(rate_map.shape[:2]) != tuple(prior_rates.shape):
            raise ValueError(
                f"local rate map {name!r} has incompatible batch/boundary shape"
            )
        _require_finite(rate_map, f"local rate map {name}")
        if bool((rate_map < 0).any()):
            raise ValueError(f"local rate map {name!r} must be non-negative")
        result = result + rate_map.to(dtype=result.dtype).sum(dim=(-2, -1))
    _require_finite(result, "conserved total rates")
    return result


class ConservedOrdinalGenerator(nn.Module):
    """Compile multi-scale feature cells into a pure-birth ordinal law.

    ``reference_count`` controls the exposure represented by a complete valid
    map at every scale.  Runtime geometry weights make the *original* valid
    map sum to this fixed exposure.  A value near the number of stride-8 cells
    retains useful dynamic range for a focal witness; the correspondingly tiny
    ``atom_rate_init`` keeps the initial image-level rate near zero.  The
    geometry weight is stored and is never recomputed during intervention.
    """

    def __init__(
        self,
        *,
        stage_channels: Mapping[str, int],
        num_classes: int = 5,
        hidden_channels: int = 128,
        evidence_scales: Optional[Sequence[str]] = None,
        reference_count: float = 4096.0,
        atom_mode: str = "cumulative",
        hybrid_cumulative_init: float = 0.9,
        atom_rate_init: float = 1e-6,
        prior_rate_init: float = 1e-4,
        boundary_scale_init: float = 1.0,
        total_rate_cap: float = 64.0,
        prior_rate_cap: float = 1.0,
        boundary_scale_cap: float = 2.0,
        rate_roundoff_margin: float = 1.0,
        dropout: float = 0.0,
    ) -> None:
        super().__init__()
        if num_classes < 2:
            raise ValueError("num_classes must be at least 2")
        if num_classes == 2:
            # Supported exactly for tests and binary ablations; the proposed
            # cumulative ordinal mechanism becomes non-trivial only at K>=3.
            pass
        if not math.isfinite(reference_count) or reference_count <= 0:
            raise ValueError("reference_count must be finite and positive")
        if not math.isfinite(total_rate_cap) or total_rate_cap <= 0.0:
            raise ValueError("total_rate_cap must be finite and positive")
        if total_rate_cap > _MAX_DECODER_RATE:
            raise ValueError(
                "total_rate_cap must not exceed the audited decoder limit "
                f"{_MAX_DECODER_RATE:g}"
            )
        if not math.isfinite(prior_rate_cap) or not 0.0 < prior_rate_cap < total_rate_cap:
            raise ValueError("prior_rate_cap must lie strictly in (0, total_rate_cap)")
        if not math.isfinite(boundary_scale_cap) or boundary_scale_cap <= 0.0:
            raise ValueError("boundary_scale_cap must be finite and positive")
        if (
            not math.isfinite(rate_roundoff_margin)
            or rate_roundoff_margin <= 0.0
            or rate_roundoff_margin >= total_rate_cap - prior_rate_cap
        ):
            raise ValueError(
                "rate_roundoff_margin must lie strictly in "
                "(0, total_rate_cap - prior_rate_cap)"
            )
        atom_mode = str(atom_mode).lower()
        if atom_mode not in _ATOM_MODES:
            raise ValueError(f"atom_mode must be one of {sorted(_ATOM_MODES)}")
        if not 0.0 < hybrid_cumulative_init < 1.0:
            raise ValueError("hybrid_cumulative_init must lie strictly in (0, 1)")
        if not stage_channels:
            raise ValueError("stage_channels must not be empty")

        available = dict(stage_channels)
        selected = tuple(available) if evidence_scales is None else tuple(evidence_scales)
        if not selected or len(set(selected)) != len(selected):
            raise ValueError("evidence_scales must contain unique stage names")
        unknown = set(selected) - set(available)
        if unknown:
            raise ValueError(f"unknown evidence scales: {sorted(unknown)}")

        self.num_classes = int(num_classes)
        self.num_boundaries = self.num_classes - 1
        self.evidence_scales = selected
        self.reference_count = float(reference_count)
        self.total_rate_cap = float(total_rate_cap)
        self.prior_rate_cap = float(prior_rate_cap)
        self.boundary_scale_cap = float(boundary_scale_cap)
        self.rate_roundoff_margin = float(rate_roundoff_margin)
        self.atom_mass_cap = (
            (
                self.total_rate_cap
                - self.prior_rate_cap
                - self.rate_roundoff_margin
            )
            / (self.reference_count * self.boundary_scale_cap)
        )
        self.atom_mode = atom_mode
        self.heads = nn.ModuleDict(
            {
                name: PointwiseSeverityAtomHead(
                    available[name],
                    hidden_channels,
                    self.num_boundaries,
                    atom_rate_init=atom_rate_init,
                    atom_mass_cap=self.atom_mass_cap,
                    atom_mode=self.atom_mode,
                    dropout=dropout,
                )
                for name in selected
            }
        )

        self.scale_simplex_logits = nn.Parameter(
            torch.zeros(len(selected), self.num_boundaries)
        )
        self.raw_boundary_scales = nn.Parameter(
            torch.full(
                (self.num_boundaries,),
                _inverse_sigmoid_fraction(
                    boundary_scale_init,
                    self.boundary_scale_cap,
                    name="boundary scale",
                ),
            )
        )
        self.raw_prior_rates = nn.Parameter(
            torch.full(
                (self.num_boundaries,),
                _inverse_sigmoid_fraction(
                    prior_rate_init,
                    self.prior_rate_cap,
                    name="prior rate",
                ),
            )
        )
        if atom_mode == "hybrid":
            mix_logit = math.log(hybrid_cumulative_init / (1.0 - hybrid_cumulative_init))
            self.atom_mix_logits = nn.Parameter(
                torch.full((self.num_boundaries,), mix_logit)
            )
        else:
            self.register_parameter("atom_mix_logits", None)

    @property
    def prior_rates(self) -> torch.Tensor:
        return self.prior_rate_cap * self.raw_prior_rates.sigmoid()

    @property
    def boundary_scales(self) -> torch.Tensor:
        return self.boundary_scale_cap * self.raw_boundary_scales.sigmoid()

    @property
    def scale_simplex(self) -> torch.Tensor:
        return self.scale_simplex_logits.softmax(dim=0)

    def _compile_atoms(self, atoms: torch.Tensor) -> torch.Tensor:
        cumulative = reverse_cumulative_atoms(atoms, dim=1)
        if self.atom_mode == "cumulative":
            return cumulative
        if self.atom_mode == "independent":
            return atoms
        if self.atom_mix_logits is None:  # pragma: no cover - constructor invariant
            raise RuntimeError("hybrid atom mode has no mixing parameters")
        mix = self.atom_mix_logits.sigmoid()[None, :, None, None]
        return mix * cumulative + (1.0 - mix) * atoms

    def forward(
        self,
        encoder_output: OriginEncoderOutput,
        *,
        force_decoder_fp64: bool = True,
        retain_encoder_output: bool = False,
    ) -> OriginOutput:
        if tuple(name for name in self.evidence_scales if name not in encoder_output.scales):
            missing = [name for name in self.evidence_scales if name not in encoder_output.scales]
            raise ValueError(f"encoder output is missing scales {missing}")

        scale_simplex = self.scale_simplex
        boundary_scales = self.boundary_scales
        _require_finite(scale_simplex, "scale simplex")
        _require_finite(boundary_scales, "boundary scales")
        scale_evidence: Dict[str, OriginScaleEvidence] = {}

        for scale_index, name in enumerate(self.evidence_scales):
            encoded: OriginEncoderScale = encoder_output.scales[name]
            features = encoded.features
            valid_mask = encoded.valid_mask
            if valid_mask.shape != features.shape[:1] + features.shape[-2:]:
                raise ValueError(f"valid mask shape mismatch at scale {name}")
            if valid_mask.dtype != torch.bool:
                valid_mask = valid_mask.bool()

            # Evidence heads are tiny relative to ConvNeXt and sit immediately
            # before the bounded atom transform and structural decoder. Keep
            # this sensitive path in FP32 even if the image trunk runs under AMP.
            with torch.autocast(device_type=features.device.type, enabled=False):
                atom_logits, atoms = self.heads[name](features.float())
                compiled = self._compile_atoms(atoms)
                original_count = valid_mask.sum(dim=(-2, -1)).to(compiled.dtype)
                geometry_weight = torch.where(
                    original_count > 0,
                    self.reference_count / original_count.clamp_min(1.0),
                    torch.zeros_like(original_count),
                )
                scale_and_boundary = (
                    scale_simplex[scale_index] * boundary_scales
                )[None, :, None, None]
                unmasked_rates = (
                    compiled
                    * scale_and_boundary
                    * geometry_weight[:, None, None, None]
                )
                local_rates = torch.where(
                    valid_mask[:, None],
                    unmasked_rates,
                    torch.zeros_like(unmasked_rates),
                )
            _require_finite(local_rates, f"local rates at {name}")
            scale_evidence[name] = OriginScaleEvidence(
                name=name,
                atom_logits=atom_logits,
                incremental_atoms=atoms,
                compiled_atoms=compiled,
                local_rate_map=local_rates,
                valid_mask=valid_mask,
                geometry_weight=geometry_weight,
                scale_weights=scale_simplex[scale_index],
                metadata=encoded.metadata,
            )

        first = scale_evidence[self.evidence_scales[0]].local_rate_map
        # Sum the stored FP32 local ledger in FP64. This makes the declared
        # roundoff reserve conservative even for the densest s4 lattice and
        # leaves the decoder on one continuous FP64 path.
        prior = self.prior_rates.to(device=first.device, dtype=_DECODER_DTYPE)
        prior = prior.unsqueeze(0).expand(first.shape[0], -1)
        total = sum_local_rate_maps(
            {name: item.local_rate_map for name, item in scale_evidence.items()},
            prior,
        )
        # The bounded atom transform, bounded scale, scale simplex, and
        # conserved geometry imply in exact arithmetic:
        #   total <= prior_cap + reference_count * scale_cap * atom_mass_cap
        #         = total_rate_cap - rate_roundoff_margin.
        maximum_total = float(total.detach().amax().item())
        if maximum_total > self.total_rate_cap:
            raise FloatingPointError(
                "ORIGIN bounded generator violated its architectural rate cap "
                f"{self.total_rate_cap:g}: {maximum_total:g}"
            )
        decoded = decode_pure_birth_rates(total, force_fp64=force_decoder_fp64)
        return _origin_output_from_decoded(
            decoded,
            scale_evidence=scale_evidence,
            prior_rates=prior,
            atom_mode=self.atom_mode,
            scale_simplex=scale_simplex,
            boundary_scales=boundary_scales,
            total_rate_cap=self.total_rate_cap,
            prior_rate_cap=self.prior_rate_cap,
            boundary_scale_cap=self.boundary_scale_cap,
            atom_mass_cap=self.atom_mass_cap,
            rate_roundoff_margin=self.rate_roundoff_margin,
            encoder_output=encoder_output if retain_encoder_output else None,
        )


@dataclass
class OriginInterventionOutput:
    """Exact internal deletion and replay of an ORIGIN evidence ledger."""

    baseline: OriginOutput
    output: OriginOutput
    removal_masks: Dict[str, torch.Tensor]
    removed_rates: torch.Tensor

    @property
    def delta_expected_grade(self) -> torch.Tensor:
        return self.baseline.expected_grade - self.output.expected_grade

    @property
    def class_probs(self) -> torch.Tensor:
        return self.output.class_probs

    @property
    def cumulative_probs(self) -> torch.Tensor:
        return self.output.cumulative_probs

    @property
    def predicted_grade(self) -> torch.Tensor:
        return self.output.predicted_grade

    @property
    def monotone_grade(self) -> torch.Tensor:
        return self.output.posterior_median


def _canonical_removal_mask(
    removal: torch.Tensor,
    target: torch.Tensor,
    *,
    name: str,
) -> torch.Tensor:
    removal = torch.as_tensor(removal, device=target.device)
    if removal.ndim == 2:
        removal = removal.unsqueeze(0)
    if removal.ndim == 4 and removal.shape[1] == 1:
        removal = removal[:, 0]
    if removal.ndim != 3:
        raise ValueError(
            f"removal mask for {name!r} must have shape (H,W), (N,H,W), "
            "or (N,1,H,W)"
        )
    if removal.shape[0] == 1 and target.shape[0] > 1:
        removal = removal.expand(target.shape[0], -1, -1)
    if tuple(removal.shape) != tuple(target.shape):
        raise ValueError(
            f"removal mask for {name!r} has shape {tuple(removal.shape)}; "
            f"expected {tuple(target.shape)}"
        )
    return removal.bool()


def replay_without(
    output: OriginOutput,
    removal_masks: Mapping[str, torch.Tensor],
    *,
    force_decoder_fp64: bool = True,
) -> OriginInterventionOutput:
    """Delete stored local contributions and replay the same CTMC decoder.

    ``True`` means delete.  Geometry weights and the original valid masks are
    copied from ``output`` and are never recalculated.  Omitting a scale means
    delete nothing at that scale.
    """

    unknown = set(removal_masks) - set(output.scale_evidence)
    if unknown:
        raise ValueError(f"removal masks contain unknown scales {sorted(unknown)}")

    replayed: Dict[str, OriginScaleEvidence] = {}
    canonical: Dict[str, torch.Tensor] = {}
    removed_rates = torch.zeros_like(output.prior_rates)
    for name, evidence in output.scale_evidence.items():
        requested = removal_masks.get(name)
        if requested is None:
            mask = torch.zeros_like(evidence.valid_mask)
        else:
            mask = _canonical_removal_mask(
                requested, evidence.valid_mask, name=name
            )
        # Removing an already-invalid cell is a well-defined no-op.
        mask = mask & evidence.valid_mask
        canonical[name] = mask
        removed_map = torch.where(
            mask[:, None],
            evidence.local_rate_map,
            torch.zeros_like(evidence.local_rate_map),
        )
        removed_rates = removed_rates + removed_map.to(
            dtype=removed_rates.dtype
        ).sum(dim=(-2, -1))
        kept = torch.where(
            mask[:, None],
            torch.zeros_like(evidence.local_rate_map),
            evidence.local_rate_map,
        )
        replayed[name] = replace(evidence, local_rate_map=kept)

    # Sum survivors rather than renormalizing or re-running any evidence head.
    replay_rates = sum_local_rate_maps(
        {name: item.local_rate_map for name, item in replayed.items()},
        output.prior_rates,
    )
    decoded = decode_pure_birth_rates(replay_rates, force_fp64=force_decoder_fp64)
    replay_output = _origin_output_from_decoded(
        decoded,
        scale_evidence=replayed,
        prior_rates=output.prior_rates,
        atom_mode=output.atom_mode,
        scale_simplex=output.scale_simplex,
        boundary_scales=output.boundary_scales,
        total_rate_cap=output.total_rate_cap,
        prior_rate_cap=output.prior_rate_cap,
        boundary_scale_cap=output.boundary_scale_cap,
        atom_mass_cap=output.atom_mass_cap,
        rate_roundoff_margin=output.rate_roundoff_margin,
        encoder_output=output.encoder_output,
    )
    return OriginInterventionOutput(
        baseline=output,
        output=replay_output,
        removal_masks=canonical,
        removed_rates=removed_rates,
    )


@dataclass
class TopKOriginInterventionReport:
    """Top-k boundary witnesses and their exact all-boundary removal effect."""

    boundary: int
    k: int
    selected_flat_indices: torch.Tensor
    selected_boundary_rates: torch.Tensor
    scale_offsets: Dict[str, Tuple[int, int]]
    intervention: OriginInterventionOutput


def topk_rate_intervention(
    output: OriginOutput,
    *,
    boundary: int,
    k: int,
    force_decoder_fp64: bool = True,
) -> TopKOriginInterventionReport:
    """Remove the k largest valid local witnesses for one boundary exactly."""

    num_boundaries = output.total_rates.shape[-1]
    if not 0 <= boundary < num_boundaries:
        raise ValueError(f"boundary must lie in [0, {num_boundaries - 1}]")
    if k < 1:
        raise ValueError("k must be positive")

    score_parts = []
    valid_parts = []
    offsets: Dict[str, Tuple[int, int]] = {}
    cursor = 0
    for name, evidence in output.scale_evidence.items():
        scores = evidence.local_rate_map[:, boundary].flatten(1)
        valid = evidence.valid_mask.flatten(1)
        score_parts.append(scores)
        valid_parts.append(valid)
        offsets[name] = (cursor, cursor + scores.shape[1])
        cursor += scores.shape[1]
    scores = torch.cat(score_parts, dim=1)
    valid = torch.cat(valid_parts, dim=1)
    if bool((valid.sum(dim=1) < k).any()):
        raise ValueError("k exceeds the valid evidence-cell count for a sample")
    ranked_scores = scores.masked_fill(~valid, -torch.inf)
    selected_scores, selected = ranked_scores.topk(k, dim=1)

    removals: Dict[str, torch.Tensor] = {}
    for name, evidence in output.scale_evidence.items():
        start, stop = offsets[name]
        flat_counts = torch.zeros_like(
            evidence.valid_mask.flatten(1), dtype=torch.int64
        )
        within = (selected >= start) & (selected < stop)
        local = (selected - start).clamp(0, stop - start - 1)
        # scatter_ can let a later false/clamped entry overwrite an earlier
        # true entry at index zero. Integer scatter-add has union semantics.
        flat_counts.scatter_add_(1, local, within.to(torch.int64))
        removals[name] = (flat_counts > 0).reshape_as(evidence.valid_mask)

    intervention = replay_without(
        output, removals, force_decoder_fp64=force_decoder_fp64
    )
    return TopKOriginInterventionReport(
        boundary=boundary,
        k=k,
        selected_flat_indices=selected,
        selected_boundary_rates=selected_scores,
        scale_offsets=offsets,
        intervention=intervention,
    )


class OriginModel(nn.Module):
    """Image-to-grade ORIGIN model with an auditable local evidence ledger."""

    def __init__(
        self,
        *,
        num_classes: int = 5,
        encoder_name: str = "convnext_tiny",
        pretrained: bool = True,
        evidence_scales: Sequence[str] = ("s4", "s8", "s16", "s32"),
        projection_dim: int = 128,
        reference_count: float = 4096.0,
        atom_mode: str = "cumulative",
        hybrid_cumulative_init: float = 0.9,
        atom_rate_init: float = 1e-6,
        prior_rate_init: float = 1e-4,
        boundary_scale_init: float = 1.0,
        total_rate_cap: float = 64.0,
        prior_rate_cap: float = 1.0,
        boundary_scale_cap: float = 2.0,
        rate_roundoff_margin: float = 1.0,
        evidence_dropout: float = 0.0,
        mask_valid_fraction: float = 0.5,
        grad_checkpoint: bool = False,
        encoder: Optional[nn.Module] = None,
    ) -> None:
        super().__init__()
        encoder_name = str(encoder_name).lower()
        if encoder_name not in {"convnext_tiny", "convnext_tiny_srff"}:
            raise ValueError(
                "ORIGIN supports encoder_name='convnext_tiny' or "
                "'convnext_tiny_srff'"
            )
        if encoder is None:
            encoder_class = (
                ConvNeXtTinySRFFEncoder
                if encoder_name == "convnext_tiny_srff"
                else ConvNeXtTinyPyramidEncoder
            )
            encoder = encoder_class(
                pretrained=pretrained,
                grad_checkpoint=grad_checkpoint,
                mask_valid_fraction=mask_valid_fraction,
            )
        if not hasattr(encoder, "STAGE_CHANNELS"):
            raise TypeError("encoder must expose a STAGE_CHANNELS mapping")
        self.encoder = encoder
        self.num_classes = int(num_classes)
        self.encoder_name = encoder_name
        self.generator = ConservedOrdinalGenerator(
            stage_channels=encoder.STAGE_CHANNELS,
            num_classes=num_classes,
            hidden_channels=projection_dim,
            evidence_scales=evidence_scales,
            reference_count=reference_count,
            atom_mode=atom_mode,
            hybrid_cumulative_init=hybrid_cumulative_init,
            atom_rate_init=atom_rate_init,
            prior_rate_init=prior_rate_init,
            boundary_scale_init=boundary_scale_init,
            total_rate_cap=total_rate_cap,
            prior_rate_cap=prior_rate_cap,
            boundary_scale_cap=boundary_scale_cap,
            rate_roundoff_margin=rate_roundoff_margin,
            dropout=evidence_dropout,
        )

    @property
    def evidence_scales(self) -> Tuple[str, ...]:
        return self.generator.evidence_scales

    def architecture_metadata(self) -> Dict[str, object]:
        """Serializable declaration recorded beside every checkpoint."""

        rate_parameterization = (
            "bounded_independent_sigmoid_v1"
            if self.generator.atom_mode == "independent"
            else "bounded_null_simplex_v1"
        )
        spatial_contract_factory = getattr(self.encoder, "spatial_contract", None)
        encoder_spatial_contract = (
            spatial_contract_factory()
            if callable(spatial_contract_factory)
            else {
                "kind": "native_convnext_pyramid_v1",
                "source_masking_inside_trunk": False,
            }
        )
        receptive_fields = {
            "s4": 76,
            "s8": 224,
            "s16": 1096,
            "s32": 1688,
            "s128": 344,
        }
        selected_receptive_fields = [
            receptive_fields[name]
            for name in self.evidence_scales
            if name in receptive_fields
        ]
        is_srff = self.encoder_name == "convnext_tiny_srff"
        return {
            "name": "ORIGIN",
            "encoder": self.encoder_name,
            "encoder_spatial_contract": encoder_spatial_contract,
            "evidence_dependency_policy": (
                "spatial_receptive_field_firewall_v1"
                if is_srff
                else "native_convnext_stage_receptive_fields"
            ),
            "srff_window_cells": (
                ConvNeXtTinySRFFEncoder.WINDOW_CELLS if is_srff else None
            ),
            "sealed_source_masking": True if is_srff else None,
            "max_evidence_receptive_field": (
                max(selected_receptive_fields) if selected_receptive_fields else None
            ),
            "num_classes": self.num_classes,
            "evidence_scales": list(self.evidence_scales),
            "atom_mode": self.generator.atom_mode,
            "reference_count": self.generator.reference_count,
            "rate_parameterization": rate_parameterization,
            "total_rate_cap": self.generator.total_rate_cap,
            "prior_rate_cap": self.generator.prior_rate_cap,
            "boundary_scale_cap": self.generator.boundary_scale_cap,
            "atom_mass_cap": self.generator.atom_mass_cap,
            "rate_roundoff_margin": self.generator.rate_roundoff_margin,
            "decoder": "fp64_taylor24_scaled_squared_pure_birth_exponential",
            "available_decisions": [
                "posterior_median",
                "class_map",
                "rounded_expected",
            ],
            "model_default_decision": "class_map",
            "run_decision_owned_by_trainer_config": True,
            "local_rate_layout": "NHW(K-1)",
            "no_classifier_bypass": True,
            "intervention": "stored_local_rate_subtraction_without_renormalization",
        }

    def forward(
        self,
        images: torch.Tensor,
        pixel_valid_mask: Optional[torch.Tensor] = None,
        *,
        force_decoder_fp64: bool = True,
        return_encoder_maps: bool = False,
    ) -> OriginOutput:
        encoded = self.encoder(images, pixel_valid_mask)
        return self.generator(
            encoded,
            force_decoder_fp64=force_decoder_fp64,
            retain_encoder_output=return_encoder_maps,
        )

    def replay_without(
        self,
        output: OriginOutput,
        removal_masks: Mapping[str, torch.Tensor],
        *,
        force_decoder_fp64: bool = True,
    ) -> OriginInterventionOutput:
        return replay_without(
            output,
            removal_masks,
            force_decoder_fp64=force_decoder_fp64,
        )

    def topk_intervention(
        self,
        output: OriginOutput,
        *,
        boundary: int,
        k: int,
        force_decoder_fp64: bool = True,
    ) -> TopKOriginInterventionReport:
        return topk_rate_intervention(
            output,
            boundary=boundary,
            k=k,
            force_decoder_fp64=force_decoder_fp64,
        )


def build_origin_model(**kwargs) -> OriginModel:
    """Stable construction hook for training and evaluation entry points."""

    return OriginModel(**kwargs)


__all__ = [
    "ChannelLayerNorm2d",
    "ConservedOrdinalGenerator",
    "OriginDecodedDistribution",
    "OriginInterventionOutput",
    "OriginModel",
    "OriginOutput",
    "OriginScaleEvidence",
    "PointwiseSeverityAtomHead",
    "TopKOriginInterventionReport",
    "build_origin_model",
    "decode_pure_birth_rates",
    "fit_pure_birth_rates",
    "pure_birth_generator",
    "replay_without",
    "reverse_cumulative_atoms",
    "sum_local_rate_maps",
    "topk_rate_intervention",
]
